import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation data with proper namespaces
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.books': 'Books',
    'nav.categories': 'Categories',
    'nav.myBooks': 'My Books',
    'nav.favorites': 'Favorites',
    'nav.history': 'History',
    'nav.profile': 'Profile',
    'nav.reviews': 'Reviews',
    'nav.dashboard': 'Dashboard',
    'nav.users': 'Users',
    'nav.adminBooks': 'Admin Books',
    'nav.adminBorrow': 'Borrow Management',
    'nav.adminReservations': 'Reservations',
    'nav.adminReservations': 'Reservations',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful',
    'auth.loginFailed': 'Login failed',
    'auth.registerFailed': 'Registration failed',
    'auth.loginRequired': 'Missing access token. Please login again.',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.total': 'Total',
    'common.status': 'Status',
    'common.actions': 'Actions',
    
    // Book Labels (for forms, fields)
    'book.label.title': 'Title',
    'book.label.author': 'Author',
    'book.label.isbn': 'ISBN',
    'book.label.category': 'Category',
    'book.label.description': 'Description',
    'book.label.publisher': 'Publisher',
    'book.label.publishedYear': 'Published Year',
    'book.label.pages': 'Pages',
    'book.label.language': 'Language',
    'book.label.uncategorized': 'Uncategorized',
    
    // Book Status
    'book.status.available': 'Available',
    'book.status.borrowed': 'Borrowed',
    'book.status.reserved': 'Reserved',
    'book.status.outOfStock': 'Out of Stock',
    'book.status.archived': 'Archived',
    'book.status.damaged': 'Damaged',
    
    // Book Actions
    'book.action.borrow': 'Borrow',
    'book.action.reserve': 'Reserve',
    'book.action.addToFavorites': 'Add to Favorites',
    'book.action.removeFromFavorites': 'Remove from Favorites',
    'book.action.writeReview': 'Write Review',
    'book.action.viewDetails': 'View Details',
    
    // Books Page
    'booksPage.title': 'Books',
    'booksPage.searchPlaceholder': 'Search books...',
    'booksPage.allCategories': 'All Categories',
    'booksPage.allAuthors': 'All Authors',
    'booksPage.allStatuses': 'All Statuses',
    'booksPage.noBooksFound': 'No books found',
    'booksPage.loading': 'Loading books...',
    'booksPage.searchError': 'Failed to load books',
    'booksPage.clearFilters': 'Clear Filters',
    'booksPage.previous': 'Previous',
    'booksPage.next': 'Next',
    'booksPage.page': 'Page',
    'booksPage.of': 'of',
    
    // Dashboard
    'dashboard.totalUsers': 'Total Users',
    'dashboard.totalBooks': 'Total Books',
    'dashboard.borrowedBooks': 'Borrowed Books',
    'dashboard.overdueBooks': 'Overdue Books',
    'dashboard.realTime': 'Real-time',
    'dashboard.inventory': 'Inventory',
    'dashboard.active': 'Active',
    'dashboard.attention': 'Attention',
    'dashboard.synchronizing': 'Synchronizing database analytics...',
    'dashboard.analyticsError': 'Analytics Engine Error',
    'dashboard.activityTimeline': 'Activity Timeline',
    'dashboard.performanceMetrics': '7-day performance metrics from live records',
    'dashboard.liveData': 'Live Data',
    'dashboard.collectionGrowth': 'Collection Growth',
    'dashboard.databaseTrend': 'Database entry trend (Weekly)',
    
    // User roles
    'role.admin': 'Admin',
    'role.librarian': 'Librarian',
    'role.user': 'User',
    
    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.overdue': 'Overdue',
    'status.returned': 'Returned',
    'status.suspended': 'Suspended',
    
    // Messages
    'message.bookBorrowed': 'Book borrowed successfully',
    'message.bookReturned': 'Book returned successfully',
    'message.bookReserved': 'Book reserved successfully',
    'message.errorOccurred': 'An error occurred',
    'message.noDataFound': 'No data found',
    
    // Date formats
    'date.today': 'Today',
    'date.yesterday': 'Yesterday',
    'date.tomorrow': 'Tomorrow',
    
    // HomePage
    'home.discover': 'Discover Your Next Favorite Book',
    'home.title': 'Browse live catalog data, borrow quickly, and track every due date in one place.',
    'home.description': 'This home page reads real data from your backend endpoints for books and borrow history.',
    'home.browseBooks': 'Browse Books',
    'home.joinNow': 'Join Now',
    'home.myBooks': 'My Books',
    'home.catalogBooks': 'Catalog books',
    'home.activeBorrows': 'Active borrows',
    'home.overdue': 'Overdue',
    'home.search': 'Search',
    'home.searchPlaceholder': 'Search books...',
    'home.categoryFilter': 'Category filter',
    'home.authorFilter': 'Author filter',
    'home.featuredBooks': 'Featured Books',
    'home.viewAll': 'View all',
    'home.loadingBooks': 'Loading books...',
    'home.noBooksFound': 'No books found from the API.',
    'home.categories': 'Categories',
    'home.booksCount': 'books',
    'home.categoryDataInfo': 'Category data will appear once books include category values.',
    'home.accountActivity': 'Account Activity',
    'home.signedInAs': 'Signed in as',
    'home.signInPrompt': 'Sign in to see your borrowing activity.',
    'home.noBorrowHistory': 'No borrow history yet.',
    'home.available': 'available',
    'home.viewDetail': 'View Detail',
    'home.uncategorized': 'Uncategorized',
    'home.general': 'General',
    'home.record': 'Record',
    
    // AuthForms
    'auth.jwtAuthentication': 'JWT Authentication',
    'auth.libraryAccess': 'Library access for users, librarians, and admins.',
    'auth.secureAuth': 'Secure authentication with role-aware navigation and real backend integration.',
    'auth.authApi': 'Auth API',
    'auth.authApiDesc': 'Register and login endpoints',
    'auth.booksApi': 'Books API',
    'auth.booksApiDesc': 'Live catalog and detail data',
    'auth.borrowApi': 'Borrow API',
    'auth.borrowApiDesc': 'Borrow, return, and history flow',
    'auth.secureAccess': 'Secure access',
    'auth.loginTitle': 'Login',
    'auth.createAccount': 'Create account',
    'auth.validationFailed': 'Validation failed',
    'auth.fixFields': 'Please fix the highlighted fields.',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInSuccess': 'You have been signed in successfully.',
    'auth.accountCreated': 'Account created',
    'auth.accountReady': 'Your account is ready to use.',
    'auth.authFailed': 'Authentication failed',
    'auth.unableToContinue': 'Unable to continue.',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Nguyen Hoang Phung',
    'auth.emailPlaceholder': 'you@library.com',
    'auth.passwordPlaceholder': '********',
    'auth.pleaseWait': 'Please wait...',
    'auth.signIn': 'Sign in',
    'auth.createAccountButton': 'Create account',
    'auth.fullNameRequired': 'Full name is required',
    'auth.emailRequired': 'Email is required',
    'auth.invalidEmail': 'Invalid email format',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    
    // DashboardCards
    'dashboardCards.totalBooks': 'Total Books',
    'dashboardCards.totalBooksDesc': 'All books in library',
    'dashboardCards.totalUsers': 'Total Users',
    'dashboardCards.totalUsersDesc': 'Registered members',
    'dashboardCards.activeBorrows': 'Active Borrows',
    'dashboardCards.activeBorrowsDesc': 'Currently borrowed books',
    'dashboardCards.overdueBooks': 'Overdue Books',
    'dashboardCards.overdueBooksDesc': 'Books overdue for return',
    
    // BookDetailPage
    'bookDetail.loading': 'Loading book details...',
    'bookDetail.error': 'Failed to load book',
    'bookDetail.backToBooks': '← Back to Books',
    'bookDetail.addToFavorites': 'Add to Favorites',
    'bookDetail.removeFromFavorites': 'Remove from Favorites',
    'bookDetail.borrow': 'Borrow',
    'bookDetail.reserve': 'Reserve',
    'bookDetail.writeReview': 'Write Review',
    'bookDetail.details': 'Details',
    'bookDetail.description': 'Description',
    'bookDetail.publisher': 'Publisher',
    'bookDetail.publishedYear': 'Published Year',
    'bookDetail.pages': 'Pages',
    'bookDetail.language': 'Language',
    'bookDetail.isbn': 'ISBN',
    'bookDetail.category': 'Category',
    'bookDetail.status': 'Status',
    'bookDetail.reviews': 'Reviews',
    'bookDetail.writeYourReview': 'Write Your Review',
    'bookDetail.yourRating': 'Your Rating',
    'bookDetail.yourReview': 'Your Review',
    'bookDetail.submitReview': 'Submit Review',
    'bookDetail.postReview': 'Post Review',
    'bookDetail.posting': 'Posting...',
    'bookDetail.loginToReview': 'Please log in to write a review',
    'bookDetail.recentReviews': 'Recent Reviews',
    'bookDetail.noReviewsYet': 'No reviews yet. Be the first!',
    'bookDetail.bookReserved': '📚 Book reserved!',
    'bookDetail.bookReservedMessage': 'Ready for pickup at the library within 48 hours. Please bring your ID to confirm and collect your book. Late returns may incur overdue fines.',
    'bookDetail.borrowFailed': 'Borrow failed',
    'bookDetail.reserved': '🔔 Reserved!',
    'bookDetail.reservedMessage': 'You will be notified when the book is available.',
    'bookDetail.reservationFailed': 'Reservation failed',
    'bookDetail.reviewSubmitted': 'Review submitted!',
    'bookDetail.reviewSubmittedMessage': 'Thank you for your feedback.',
    'bookDetail.failedToSubmit': 'Failed to submit',
    'bookDetail.failedLoadBook': 'Failed to load book data',
    'bookDetail.available': 'Available',
    'bookDetail.unavailable': 'Unavailable',
    'bookDetail.noRatings': 'No ratings',
    'bookDetail.bookNotFound': 'Book not found',
    'bookDetail.saved': 'Saved',
    'bookDetail.save': 'Save',
    'bookDetail.addedToFavorites': 'Added to favorites',
    'bookDetail.removedFromFavorites': 'Removed from favorites',
    'bookDetail.share': 'Share',
    'bookDetail.linkCopied': 'Link copied!',
    'bookDetail.quantity': 'Quantity',
    'bookDetail.year': 'Year',
    'bookDetail.processing': 'Processing...',
    'bookDetail.borrowNow': 'Borrow Now',
    'bookDetail.reserveBook': 'Reserve Book',
    'bookDetail.peopleInQueue': 'people in queue',
    'bookDetail.howRate': 'How would you rate this book?',
    'bookDetail.reviewTitle': 'Review Title',
    'bookDetail.reviewPlaceholder': 'Share your thoughts about this book...',
    
    // MyBorrowsPage
    'myBorrows.title': 'My Books',
    'myBorrows.dataFrom': 'Data from `/api/v1/borrows/history`.',
    'myBorrows.borrowed': 'Borrowed',
    'myBorrows.returned': 'Returned',
    'myBorrows.overdue': 'Overdue',
    'myBorrows.loadingRecords': 'Loading records...',
    'myBorrows.book': 'Book',
    'myBorrows.borrowDate': 'Borrow Date',
    'myBorrows.dueDate': 'Due Date',
    'myBorrows.returnDate': 'Return Date',
    'myBorrows.daysLeft': 'Days Left',
    'myBorrows.overdueBy': 'Overdue by',
    'myBorrows.extend': 'Extend',
    'myBorrows.return': 'Return',
    'myBorrows.noBorrowRecords': 'No borrow records found.',
    'myBorrows.extendSuccess': 'Loan extended successfully',
    'myBorrows.extendFailed': 'Failed to extend loan',
    'myBorrows.returnSuccess': 'Book returned successfully',
    'myBorrows.returnFailed': 'Failed to return book',
    'myBorrows.status': 'Status',
    'myBorrows.action': 'Action',
    'myBorrows.noRecords': 'No records found.',
    'myBorrows.loadFailed': 'Failed to load records',
    'myBorrows.loadFailedMessage': 'Unable to load borrow records.',
    'myBorrows.extended': 'Extended',
    'myBorrows.extendedMessage': 'Loan extended successfully',
    'myBorrows.extendFailedMessage': 'Failed to extend loan',
    'myBorrows.returnedMessage': 'Book returned successfully',
    'myBorrows.returnFailedMessage': 'Failed to return book',
    
    // BorrowConfirmModal
    'borrowConfirm.title': 'Confirm Borrow',
    'borrowConfirm.confirmBorrow': 'Confirm Borrow',
    'borrowConfirm.borrowDetails': 'Borrow Details',
    'borrowConfirm.book': 'Book',
    'borrowConfirm.borrowDate': 'Borrow Date',
    'borrowConfirm.dueDate': 'Due Date',
    'borrowConfirm.borrowPeriod': 'Borrow Period',
    'borrowConfirm.days': 'days',
    'borrowConfirm.borrowing': 'Borrowing...',
    'borrowConfirm.borrowSuccess': 'Book borrowed successfully!',
    'borrowConfirm.borrowFailed': 'Failed to borrow book',
    'borrowConfirm.close': 'Close',
    
    // BookTable
    'bookTable.title': 'Books Management',
    'bookTable.addBook': 'Add Book',
    'bookTable.searchBooks': 'Search books',
    'bookTable.searchTitleAuthorCategory': 'Search title, author, category',
    'bookTable.searchPlaceholder': 'Search books...',
    'bookTable.filterByCategory': 'Filter by Category',
    'bookTable.filterByAuthor': 'Filter by Author',
    'bookTable.filterByStatus': 'Filter by Status',
    'bookTable.clearFilters': 'Clear Filters',
    'bookTable.addNewBook': 'Add New Book',
    'bookTable.bookTitle': 'Book Title',
    'bookTable.author': 'Author',
    'bookTable.isbn': 'ISBN',
    'bookTable.category': 'Category',
    'bookTable.status': 'Status',
    'bookTable.available': 'Available',
    'bookTable.outOfStock': 'Out of Stock',
    'bookTable.archived': 'Archived',
    'bookTable.damaged': 'Damaged',
    'bookTable.noBooksFound': 'No books found',
    'bookTable.loading': 'Loading books...',
    'bookTable.edit': 'Edit',
    'bookTable.delete': 'Delete',
    'bookTable.showing': 'Showing {count} of {total} books',
    'bookTable.prev': 'Prev',
    'bookTable.next': 'Next',
    'bookTable.editBook': 'Edit Book',
    'bookTable.addBookTitle': 'Add Book',
    'bookTable.totalQuantity': 'Total Quantity',
    'bookTable.saveBook': 'Save Book',
    'bookTable.cancel': 'Cancel',
    'bookTable.deleteBook': 'Delete Book',
    'bookTable.confirmDelete': 'Are you sure you want to delete this book?',
    'bookTable.deleting': 'Deleting...',
    'bookTable.bookDeleted': 'Book deleted successfully',
    'bookTable.deleteFailed': 'Failed to delete book',
    'bookTable.saved': 'Book saved successfully',
    'bookTable.saveFailed': 'Failed to save book',
    'bookTable.stock': 'Stock',
    'bookTable.loadFailedFallback': 'Unable to load books from API. Showing fallback data.',
    'bookTable.requiredFields': 'Title, ISBN and total quantity are required.',
    
    // UserTable
    'userTable.title': 'Users Management',
    'userTable.addUser': 'Add User',
    'userTable.searchPlaceholder': 'Search users...',
    'userTable.filterByRole': 'Filter by Role',
    'userTable.filterByStatus': 'Filter by Status',
    'userTable.clearFilters': 'Clear Filters',
    'userTable.addNewUser': 'Add New User',
    'userTable.fullName': 'Full Name',
    'userTable.email': 'Email',
    'userTable.role': 'Role',
    'userTable.status': 'Status',
    'userTable.active': 'Active',
    'userTable.inactive': 'Inactive',
    'userTable.noUsersFound': 'No users found',
    'userTable.loading': 'Loading users...',
    'userTable.edit': 'Edit',
    'userTable.delete': 'Delete',
    'userTable.showing': 'Showing {count} of {total} users',
    'userTable.prev': 'Prev',
    'userTable.next': 'Next',
    'userTable.addUserTitle': 'Add User',
    'userTable.editUserTitle': 'Edit User',
    'userTable.saveUser': 'Save User',
    'userTable.cancel': 'Cancel',
    'userTable.deleteUser': 'Delete User',
    'userTable.confirmDelete': 'Are you sure you want to delete this user?',
    'userTable.deleting': 'Deleting...',
    'userTable.userDeleted': 'User deleted successfully',
    'userTable.deleteFailed': 'Failed to delete user',
    'userTable.saved': 'User saved successfully',
    'userTable.saveFailed': 'Failed to save user',
    'userTable.searchUsers': 'Search users',
    'userTable.searchNameEmail': 'Search name, email',
    'userTable.addUserButton': 'Add User',
    'userTable.fullNameHeader': 'Full Name',
    'userTable.emailHeader': 'Email',
    'userTable.roleHeader': 'Role',
    'userTable.statusHeader': 'Status',
    'userTable.lastLoginHeader': 'Last Login',
    'userTable.actionsHeader': 'Actions',
    'userTable.loadingUsers': 'Loading users...',
    'userTable.editButton': 'Edit',
    'userTable.deleteButton': 'Delete',
    'userTable.passwordLabel': 'Password',
    'userTable.passwordOptional': 'Password (leave blank to keep current)',
    'userTable.loadFailed': 'Unable to load users.',
    'userTable.fullNameEmailRequired': 'Full name and email are required.',
    'userTable.passwordRequiredCreate': 'Password is required when creating user.',
    
    // AdminDashboard
    'adminDashboard.controlPanel': 'Admin Control Panel',
    'adminDashboard.welcomeBack': 'Welcome back, {name}!',
    'adminDashboard.yourRole': 'Your role: {role} | Manage your library operations efficiently',
    'adminDashboard.bookManagement': 'Book Management',
    'adminDashboard.bookManagementDesc': 'Add, edit, delete books and manage inventory',
    'adminDashboard.userManagement': 'User Management',
    'adminDashboard.userManagementDesc': 'Manage users, roles and permissions',
    'adminDashboard.borrowManagement': 'Borrow Management',
    'adminDashboard.borrowManagementDesc': 'Track and manage book borrowing requests',
    'adminDashboard.borrowWorkflow': 'Borrow Workflow',
    'adminDashboard.borrowWorkflowDesc': 'Process borrow requests and manage returns',
    'adminDashboard.reservationManagement': 'Reservation Management',
    'adminDashboard.reservationManagementDesc': 'Handle book reservations and notifications',
    'adminDashboard.reservations': 'Reservations',
    'adminDashboard.reservationsDesc': 'View and manage book reservations',
    'adminDashboard.systemSettings': 'System Settings',
    'adminDashboard.systemSettingsDesc': 'Configure policies, fines and notifications',
    'adminDashboard.open': 'Open',
    'adminDashboard.systemStatus': 'System Status',
    'adminDashboard.backend': 'Backend: {status}',
    'adminDashboard.checking': 'Checking...',
    'adminDashboard.connected': 'Connected - API is working',
    'adminDashboard.error': 'Error: {error}',
    'adminDashboard.online': 'Online',
    'adminDashboard.offline': 'Offline',
    
    // LibrarianDashboard
    'librarianDashboard.workstation': 'Librarian Workstation',
    'librarianDashboard.welcome': 'Welcome, {name}!',
    'librarianDashboard.roleDesc': 'Role: {role} | Process borrow requests and manage returns',
    'librarianDashboard.pendingApprovals': 'Pending Approvals',
    'librarianDashboard.overdueBooks': 'Overdue Books',
    'librarianDashboard.dueToday': 'Due Today',
    'librarianDashboard.noPending': 'No pending borrow requests',
    'librarianDashboard.noOverdue': 'No overdue books',
    'librarianDashboard.noDueToday': 'No books due today',
    'librarianDashboard.approve': 'Approve',
    'librarianDashboard.reject': 'Reject',
    'librarianDashboard.confirmReturn': 'Confirm Return',
    'librarianDashboard.processing': 'Processing...',
    'librarianDashboard.approved': 'Request approved',
    'librarianDashboard.rejected': 'Request rejected',
    'librarianDashboard.returned': 'Book returned',
    'librarianDashboard.failed': 'Operation failed',
    'librarianDashboard.pendingBorrowRequests': 'Pending Borrow Requests',
    'librarianDashboard.reviewAndApprove': 'Review and approve borrow requests',
    'librarianDashboard.noPendingRequests': 'No pending requests',
    'librarianDashboard.requiresAttention': 'Requires attention',
    'librarianDashboard.overdueBooksTitle': 'Overdue Books',
    'librarianDashboard.booksPastDue': 'Books past due date requiring action',
    'librarianDashboard.noBooksDueToday': 'No books due today',
    'librarianDashboard.enterRejectionReason': 'Enter rejection reason (optional):',
    'librarianDashboard.loading': 'Loading...',
    'librarianDashboard.refresh': 'Refresh',
    
    // BookCoverUpload
    'bookCoverUpload.onlyJpgPngWebp': 'Only JPG, PNG, WEBP supported.',
    'bookCoverUpload.maxSize2mb': 'Maximum file size is 2MB.',
    'bookCoverUpload.uploadFailed': 'Upload failed with status {status}',
    'bookCoverUpload.uploadError': 'Error uploading file.',
    'bookCoverUpload.downloadFailed': 'Download failed with status {status}',
    'bookCoverUpload.downloadError': 'Error downloading image from URL.',
    'bookCoverUpload.deleteFailed': 'Delete failed',
    'bookCoverUpload.deleteError': 'Error deleting cover image.',
    'bookCoverUpload.confirmDelete': 'Are you sure you want to delete this cover image?',
    'bookCoverUpload.coverPreview': 'Cover Preview',
    'bookCoverUpload.noCover': 'No cover image',
    'bookCoverUpload.manageCover': 'Manage Cover Image',
    'bookCoverUpload.dragDropOrClick': 'Drag and drop or click to select file',
    'bookCoverUpload.supportedFormats': 'JPG, PNG, WEBP up to 2MB',
    'bookCoverUpload.enterUrl': 'Enter URL to download',
    'bookCoverUpload.download': 'Download',
    'bookCoverUpload.cancel': 'Cancel',
    'bookCoverUpload.deleteImage': 'Delete Image',
    
    // BorrowManagement
    'borrowManagement.unableToLoad': 'Unable to load borrow records.',
    'borrowManagement.approved': 'Approved',
    'borrowManagement.approvedMessage': 'Borrow request approved!',
    'borrowManagement.rejected': 'Rejected',
    'borrowManagement.rejectedMessage': 'Borrow request rejected.',
    'borrowManagement.returned': 'Returned',
    'borrowManagement.returnedMessage': 'Book returned successfully.',
    'borrowManagement.extended': 'Extended',
    'borrowManagement.extendedMessage': 'Loan extended by 7 days.',
    'borrowManagement.error': 'Error',
    'borrowManagement.rejectReason': 'Rejection reason (optional):',
    'borrowManagement.activeBorrows': 'Active borrows',
    'borrowManagement.overdueItems': 'Overdue items',
    'borrowManagement.returnedItems': 'Returned items',
    'borrowManagement.searchRecords': 'Search borrowing records',
    'borrowManagement.searchPlaceholder': 'Search user, book or status',
    'borrowManagement.all': 'All',
    'borrowManagement.pending': 'Pending',
    'borrowManagement.borrowed': 'Borrowed',
    'borrowManagement.returned': 'Returned',
    'borrowManagement.overdue': 'Overdue',
    'borrowManagement.loading': 'Loading borrow records...',
    'borrowManagement.noRecords': 'No records found.',
    'borrowManagement.borrower': 'Borrower',
    'borrowManagement.borrowDate': 'Borrow date',
    'borrowManagement.dueDate': 'Due date',
    'borrowManagement.approve': 'Approve',
    'borrowManagement.reject': 'Reject',
    'borrowManagement.return': 'Return',
    'borrowManagement.extend': 'Extend',
    
    // ReservationTable
    'reservationTable.failedToLoad': 'Failed to load reservations',
    'reservationTable.bookReservations': 'Book Reservations',
    'reservationTable.allStatuses': 'All Statuses',
    'reservationTable.active': 'Active',
    'reservationTable.fulfilled': 'Fulfilled',
    'reservationTable.cancelled': 'Cancelled',
    'reservationTable.expired': 'Expired',
    'reservationTable.loading': 'Loading reservations...',
    'reservationTable.noReservations': 'No reservations found.',
    'reservationTable.book': 'Book',
    'reservationTable.user': 'User',
    'reservationTable.priority': 'Priority',
    'reservationTable.status': 'Status',
    'reservationTable.reservedAt': 'Reserved At',
    'reservationTable.expiresAt': 'Expires At',
    'reservationTable.actions': 'Actions',
    'reservationTable.normal': 'Normal',
    'reservationTable.high': 'High',
    'reservationTable.urgent': 'Urgent',
    'reservationTable.fulfill': 'Fulfill',
    'reservationTable.cancel': 'Cancel',
    'reservationTable.confirmCancel': 'Are you sure you want to cancel this reservation?',
    'reservationTable.confirmFulfill': 'Mark this reservation as fulfilled?',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.userManagement': 'User Management',
    'sidebar.bookService': 'Book Service',
    'sidebar.borrowService': 'Borrow Service',
    'sidebar.reservations': 'Reservations',
    'sidebar.settings': 'Settings',
    'sidebar.workDashboard': 'Work Dashboard',
    'sidebar.borrowRequests': 'Borrow Requests',
    'sidebar.bookInventory': 'Book Inventory',
    'sidebar.profile': 'Profile',
    'sidebar.adminSuite': 'Admin Suite',
    'sidebar.librarianSuite': 'Librarian Suite',
    'sidebar.library': 'Library',
    'sidebar.signedInAs': 'Signed in as',
    'sidebar.adminUser': 'Admin User',
    'sidebar.lightMode': 'Light Mode',
    'sidebar.darkMode': 'Dark Mode',

    // CategoriesPage
    'categoriesPage.title': 'Categories',
    'categoriesPage.description': 'Aggregated from `/api/v1/books` response.',
    'categoriesPage.loading': 'Loading categories...',
    'categoriesPage.noCategories': 'No categories found',
    'categoriesPage.uncategorized': 'Uncategorized',
    'categoriesPage.booksCount': 'books',

    // FavoritesPage
    'favoritesPage.title': 'Favorites',
    'favoritesPage.description': 'Uses local favorite IDs and fetches each book from API.',
    'favoritesPage.loading': 'Loading favorites...',
    'favoritesPage.noFavorites': 'No favorite books yet',
    'favoritesPage.addToFavorites': 'Add books to your favorites to see them here',

    // ProfilePage
    'profilePage.title': 'Profile',
    'profilePage.description': 'Current identity from authenticated token payload.',
    'profilePage.fullName': 'Full name',
    'profilePage.email': 'Email',
    'profilePage.role': 'Role',
    'profilePage.userId': 'User ID',
    'profilePage.editNotAvailable': 'Edit profile endpoint is not available yet in the current backend API.',

    // HistoryPage
    'historyPage.title': 'History',
    'historyPage.description': 'Your complete borrowing history',
    'historyPage.loading': 'Loading history...',
    'historyPage.noHistory': 'No history available',

    // ReviewsPage
    'reviewsPage.title': 'Reviews',
    'reviewsPage.description': 'Your book reviews and ratings',
    'reviewsPage.loading': 'Loading reviews...',
    'reviewsPage.noReviews': 'No reviews yet',
    'reviewsPage.writeFirstReview': 'Write your first review',

    // ReservationsPage
    'reservationsPage.title': 'Reservations',
    'reservationsPage.description': 'Manage your book reservations',
    'reservationsPage.loading': 'Loading reservations...',
    'reservationsPage.noReservations': 'No reservations found',
    'reservationsPage.makeReservation': 'Make Reservation',
    'reservationsPage.cancelReservation': 'Cancel Reservation',

    // BorrowBookPage
    'borrowBookPage.title': 'Borrow Book',
    'borrowBookPage.description': 'Borrow a book from the library',
    'borrowBookPage.selectBook': 'Select a book to borrow',
    'borrowBookPage.borrowPeriod': 'Borrow Period',
    'borrowBookPage.confirmBorrow': 'Confirm Borrow',

    // BorrowPage
    'borrowPage.title': 'Borrow',
    'borrowPage.description': 'Borrow management',
    'borrowPage.loading': 'Loading...',

    // BookPage
    'bookPage.title': 'Book',
    'bookPage.description': 'Book details and information',
    'bookPage.loading': 'Loading book...',

    // DashboardPage
    'dashboardPage.title': 'Dashboard',
    'dashboardPage.description': 'Library management dashboard',
    'dashboardPage.loading': 'Loading dashboard...',

    // UserPage
    'userPage.title': 'User',
    'userPage.description': 'User management',
    'userPage.loading': 'Loading user...',

    // AdminHomePageLegacy
    'adminHomePageLegacy.title': 'Admin Home',
    'adminHomePageLegacy.description': 'Legacy admin home page',

    // ThemeToggle
    'themeToggle.light': 'Light',
    'themeToggle.dark': 'Dark',
    'themeToggle.toggleTheme': 'Toggle theme',

    // Toast
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.warning': 'Warning',
    'toast.info': 'Info',

    // Input
    'input.required': 'Required',
    'input.optional': 'Optional',

    // Dropdown
    'dropdown.selectOption': 'Select an option',
    'dropdown.noOptions': 'No options available',

    // Modal
    'modal.close': 'Close',

    // Layout
    'layout.loading': 'Loading...',
    'layout.error': 'Error loading content',

    // Login
    'login.title': 'Login',
    'login.description': 'Sign in to your account',

    // DashboardLayout
    'dashboardLayout.loading': 'Loading dashboard...',
    'dashboardLayout.error': 'Error loading dashboard',

    // RoleBasedDashboard
    'roleBasedDashboard.loading': 'Loading dashboard...',
    'roleBasedDashboard.error': 'Error loading dashboard',

    // DashboardCards
    'dashboardCards.loading': 'Loading stats...',
    'dashboardCards.error': 'Error loading stats',

    // AuthForms
    'auth.jwtAuthentication': 'JWT Authentication',
    'auth.libraryAccess': 'Library access for users, librarians, and admins.',
    'auth.secureAuth': 'Secure authentication with role-aware navigation and real backend integration.',
    'auth.authApi': 'Auth API',
    'auth.authApiDesc': 'Register and login endpoints',
    'auth.booksApi': 'Books API',
    'auth.booksApiDesc': 'Live catalog and detail data',
    'auth.borrowApi': 'Borrow API',
    'auth.borrowApiDesc': 'Borrow, return, and history flow',
    'auth.secureAccess': 'Secure access',
    'auth.loginTitle': 'Login',
    'auth.createAccount': 'Create account',
    'auth.validationFailed': 'Validation failed',
    'auth.fixFields': 'Please fix the highlighted fields.',
    'auth.signInSuccess': 'You have been signed in successfully.',
    'auth.accountCreated': 'Account created',
    'auth.accountReady': 'Your account is ready to use.',
    'auth.authFailed': 'Authentication failed',
    'auth.unableToContinue': 'Unable to continue.',
    'auth.signIn': 'Sign in',
    'auth.createAccountButton': 'Create account',
    'auth.fullNamePlaceholder': 'Nguyen Hoang Phung',
    'auth.emailPlaceholder': 'you@library.com',
    'auth.passwordPlaceholder': '********',
    'auth.pleaseWait': 'Please wait...',
    'auth.fullNameRequired': 'Full name is required',
    'auth.invalidEmail': 'Invalid email format',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.dontHaveAccount': "Don't have an account? ",
    'auth.alreadyHaveAccount': 'Already have an account? ',

    // BookCoverUpload
    'bookCoverUpload.onlyJpgPngWebp': 'Only supports JPG, PNG, WEBP.',
    'bookCoverUpload.maxSize2mb': 'Max size 2MB.',
    'bookCoverUpload.uploadFailed': 'Upload failed with status {status}',
    'bookCoverUpload.uploadError': 'Error when uploading.',
    'bookCoverUpload.downloadFailed': 'Download failed with status {status}',
    'bookCoverUpload.downloadError': 'Error when downloading image from URL.',
    'bookCoverUpload.deleteFailed': 'Delete failed',
    'bookCoverUpload.deleteError': 'Error when deleting cover image.',
    'bookCoverUpload.confirmDelete': 'Are you sure you want to delete this cover image?',
    'bookCoverUpload.coverPreview': 'Cover Preview',
    'bookCoverUpload.noCover': 'No cover',
    'bookCoverUpload.manageCover': 'Manage Cover',
    'bookCoverUpload.dragDropOrClick': 'Drag drop or Click select file',
    'bookCoverUpload.supportedFormats': 'JPG, PNG, WEBP up to 2MB',
    'bookCoverUpload.enterUrl': 'Enter URL to download',
    'bookCoverUpload.download': 'Download',
    'bookCoverUpload.deleteImage': 'Delete image',

    // Common
    'common.overview': 'Overview',

    // Additional missing keys for components
    'bookTable.stock': 'Inventory',
    'bookTable.saved': 'Saved',
    'bookTable.saveFailed': 'Save failed',
    'bookTable.confirmDelete': 'Are you sure you want to delete this book?',
    'bookTable.bookDeleted': 'Book deleted',
    'bookTable.deleteFailed': 'Delete failed',
    'bookTable.bookTitle': 'Book Title',
    'bookTable.author': 'Author',
    'bookTable.category': 'Category',
    'bookTable.isbn': 'ISBN',
    'bookTable.status': 'Status',
    'bookTable.actions': 'Actions',
    'bookTable.filterByCategory': 'Filter by category',
    'bookTable.filterByAuthor': 'Filter by author',
    'bookTable.filterByStatus': 'Filter by status',
    'bookTable.clearFilters': 'Clear filters',
    'bookTable.totalQuantity': 'Total quantity',
    'bookTable.saveBook': 'Save Book',
    'bookTable.prev': 'Prev',
    'bookTable.next': 'Next',
    'bookTable.showing': 'Showing {count} of {total} {total, plural, one {book} other {books}}',
    'bookTable.available': 'Available',
    'bookTable.outOfStock': 'Out of Stock',
    'bookTable.archived': 'Archived',
    'bookTable.damaged': 'Damaged',
    'bookTable.editBook': 'Edit Book',
    'bookTable.addBookTitle': 'Add Book',

    'borrowConfirm.title': 'Confirm Request',
    'borrowConfirm.confirmBorrow': 'Borrow this book',
    'borrowConfirm.borrowDate': 'Borrow',
    'borrowConfirm.dueDate': 'Due',
    'borrowConfirm.borrowPeriod': 'Extensions',
    'borrowConfirm.days': 'days',
    'borrowConfirm.borrowing': 'Submitting...',

    'borrowManagement.activeBorrows': 'Active borrows',
    'borrowManagement.overdueItems': 'Overdue items',
    'borrowManagement.returnedItems': 'Returned items',
    'borrowManagement.all': 'All',
    'borrowManagement.pending': 'Pending',
    'borrowManagement.borrowed': 'Borrowed',
    'borrowManagement.returned': 'Returned',
    'borrowManagement.overdue': 'Overdue',
    'borrowManagement.searchRecords': 'Search borrowing records',
    'borrowManagement.searchPlaceholder': 'Search user, book or status',
    'borrowManagement.loading': 'Loading borrow records...',
    'borrowManagement.noRecords': 'No records found.',
    'borrowManagement.borrower': 'Borrower',
    'borrowManagement.borrowDate': 'Borrow date',
    'borrowManagement.dueDate': 'Due date',
    'borrowManagement.approve': 'Approve',
    'borrowManagement.reject': 'Reject',
    'borrowManagement.return': 'Return',
    'borrowManagement.extend': 'Extend',
    'borrowManagement.approved': 'Approved',
    'borrowManagement.approvedMessage': 'Borrow request approved!',
    'borrowManagement.rejected': 'Rejected',
    'borrowManagement.rejectedMessage': 'Borrow request rejected.',
    'borrowManagement.returned': 'Returned',
    'borrowManagement.returnedMessage': 'Book returned successfully.',
    'borrowManagement.extended': 'Extended',
    'borrowManagement.extendedMessage': 'Loan extended by 7 days.',
    'borrowManagement.error': 'Error',
    'borrowManagement.unableToLoad': 'Unable to load borrow records.',
    'borrowManagement.rejectReason': 'Reason for rejection (optional):',

    'reservationTable.bookReservations': 'Book Reservations',
    'reservationTable.allStatuses': 'All Statuses',
    'reservationTable.active': 'Active',
    'reservationTable.fulfilled': 'Fulfilled',
    'reservationTable.cancelled': 'Cancelled',
    'reservationTable.expired': 'Expired',
    'reservationTable.book': 'Book',
    'reservationTable.user': 'User',
    'reservationTable.priority': 'Priority',
    'reservationTable.status': 'Status',
    'reservationTable.reservedAt': 'Reserved At',
    'reservationTable.expiresAt': 'Expires At',
    'reservationTable.actions': 'Actions',
    'reservationTable.loading': 'Loading reservations...',
    'reservationTable.noReservations': 'No reservations found.',
    'reservationTable.failedToLoad': 'Failed to load reservations',
    'reservationTable.confirmCancel': 'Are you sure you want to cancel this reservation?',
    'reservationTable.confirmFulfill': 'Mark this reservation as fulfilled?',
    'reservationTable.fulfill': 'Fulfill',
    'reservationTable.cancel': 'Cancel',
    'reservationTable.normal': 'Normal',
    'reservationTable.high': 'High',
    'reservationTable.urgent': 'Urgent',

    'userTable.searchUsers': 'Search users',
    'userTable.searchNameEmail': 'Search name, email',
    'userTable.status': 'Status',
    'userTable.addUserButton': 'Add User',
    'userTable.fullNameHeader': 'Full Name',
    'userTable.emailHeader': 'Email',
    'userTable.roleHeader': 'Role',
    'userTable.statusHeader': 'Status',
    'userTable.lastLoginHeader': 'Last Login',
    'userTable.actionsHeader': 'Actions',
    'userTable.loadingUsers': 'Loading users...',
    'userTable.editButton': 'Edit',
    'userTable.deleteButton': 'Delete',
    'userTable.showing': 'Showing {count} of {total} users',
    'userTable.addUserTitle': 'Add User',
    'userTable.editUserTitle': 'Edit User',
    'userTable.passwordOptional': 'Password (leave blank to keep current)',
    'userTable.saveUser': 'Save User',
    'userTable.saveFailed': 'Unable to save user.',
    'userTable.deleteFailed': 'Unable to delete user.',

    // AdminDashboard
    'adminDashboard.checking': 'Checking...',
    'adminDashboard.connected': 'Connected - API is working',
    'adminDashboard.error': 'Error: HTTP {status}',
    'adminDashboard.controlPanel': 'Admin Control Panel',
    'adminDashboard.welcomeBack': 'Welcome back, {name}',
    'adminDashboard.yourRole': 'Your role: ',
    'adminDashboard.manageOperations': '| Manage your library operations efficiently',
    'adminDashboard.bookManagement': 'Book Management',
    'adminDashboard.bookManagementDesc': 'Add, edit, delete books and manage inventory',
    'adminDashboard.userManagement': 'User Management',
    'adminDashboard.userManagementDesc': 'Manage user accounts, roles and permissions',
    'adminDashboard.borrowWorkflow': 'Borrow Workflow',
    'adminDashboard.borrowWorkflowDesc': 'Track borrow requests, returns and overdue',
    'adminDashboard.reservationsDesc': 'Manage book reservations and waiting list',
    'adminDashboard.systemSettings': 'System Settings',
    'adminDashboard.systemSettingsDesc': 'Configure policies, fines and notifications',
    'adminDashboard.open': 'Open',
    'adminDashboard.systemStatus': 'System Status',
    'adminDashboard.backend': 'Backend: ',
    'adminDashboard.online': 'Online',
    'adminDashboard.offline': 'Offline',

    // BookDetail
    'bookDetail.borrowSuccess': 'Book borrowed successfully',
    'bookDetail.borrowSuccessMessage': 'You have successfully borrowed this book.',
    'bookDetail.reserveSuccess': 'Book reserved successfully',
    'bookDetail.reserveSuccessMessage': 'Your reservation has been confirmed.',
    'bookDetail.reviewValidationFailed': 'Review validation failed',
    'bookDetail.reviewValidationMessage': 'Please provide a rating and both title and content.',
    'bookDetail.reviewPosted': 'Review posted',
    'bookDetail.reviewPostedMessage': 'Your review has been posted successfully.',
    'bookDetail.bookNotFound': 'Book Not Found',
    'bookDetail.bookNotFoundMessage': 'The book you are looking for does not exist.',
    'bookDetail.backToBooks': 'Back to Books',
    'bookDetail.available': 'Available',
    'bookDetail.unavailable': 'Unavailable',
    'bookDetail.backToBooks': 'Back to Books',
    'bookDetail.linkCopied': 'Link copied',
    'bookDetail.share': 'Share',
    'bookDetail.quantity': 'Quantity',
    'bookDetail.year': 'Year',
    'bookDetail.isbn': 'ISBN',
    'bookDetail.description': 'Description',
    'bookDetail.borrowNow': 'BORROW NOW',
    'bookDetail.processing': 'Processing...',
    'bookDetail.reserveBook': 'RESERVE BOOK',
    'bookDetail.peopleInQueue': '{count} people in queue',
    'bookDetail.writeReview': 'Write a Review',
    'bookDetail.howRate': 'How would you rate it?',
    'bookDetail.reviewTitlePlaceholder': 'Title of your review',
    'bookDetail.reviewContentPlaceholder': 'Share your experience with this book...',
    'bookDetail.posting': 'Posting...',
    'bookDetail.postReview': 'Post Review',
    'bookDetail.loginToReview': 'Please log in to write a review',
    'bookDetail.recentReviews': 'Recent Reviews',
    'bookDetail.noReviews': 'No reviews yet. Be the first!',

    // BooksPage
    'booksPage.category': 'Category',
    'booksPage.author': 'Author',
    'booksPage.availability': 'Availability',
    'booksPage.allCategories': 'All Categories',
    'booksPage.allAuthors': 'All Authors',
    'booksPage.allStatuses': 'All Statuses',
    'booksPage.searchPlaceholder': 'Search by title, author, or ISBN...',
    'booksPage.loading': 'Loading books...',
    'booksPage.failedToLoad': 'Failed to load books',
    'booksPage.viewDetail': 'View Detail',
    'booksPage.noBooksFound': 'No books found.',
    'booksPage.page': 'Page {current} / {total}',

    // HomePage
    'homePage.discoverNextBook': 'Discover Your Next Favorite Book',
    'homePage.browseDescription': 'Browse live catalog data, borrow quickly, and track every due date in one place.',
    'homePage.readRealData': 'This home page reads real data from your backend endpoints for books and borrow history.',
    'homePage.browseBooks': 'Browse Books',
    'homePage.joinNow': 'Join Now',
    'homePage.catalogBooks': 'Catalog books',
    'homePage.activeBorrows': 'Active borrows',
    'homePage.overdue': 'Overdue',
    'homePage.search': 'Search',
    'homePage.searchBooks': 'Search books...',
    'homePage.categoryFilter': 'Category filter',
    'homePage.authorFilter': 'Author filter',
    'homePage.featuredBooks': 'Featured Books',
    'homePage.viewAll': 'View all',
    'homePage.loadingBooks': 'Loading books...',
    'homePage.available': 'available',
    'homePage.noBooksFound': 'No books found from the API.',
    'homePage.accountActivity': 'Account Activity',
    'homePage.signedInAs': 'Signed in as {name}',
    'homePage.signInToSeeActivity': 'Sign in to see your borrowing activity.',
    'homePage.record': 'Record',
    'homePage.noBorrowHistory': 'No borrow history yet.',
    'homePage.categoryDataWillAppear': 'Category data will appear once books include category values.',

    // LibrarianDashboard
    'librarianDashboard.librarianPanel': 'Librarian Control Panel',
    'librarianDashboard.welcomeBack': 'Welcome back, {name}',
    'librarianDashboard.manageLibrary': 'Manage library operations and assist users efficiently.',
    'librarianDashboard.totalBooks': 'Total Books',
    'librarianDashboard.activeBorrows': 'Active Borrows',
    'librarianDashboard.pendingApprovals': 'Pending Approvals',
    'librarianDashboard.overdueItems': 'Overdue Items',
    'librarianDashboard.requiresAttention': 'Requires attention',
    'librarianDashboard.pendingRequests': 'Pending Borrow Requests',
    'librarianDashboard.reviewApprove': 'Review and approve borrow requests',
    'librarianDashboard.user': 'User',
    'librarianDashboard.book': 'Book',
    'librarianDashboard.requestDate': 'Request Date',
    'librarianDashboard.actions': 'Actions',
    'librarianDashboard.noPendingRequests': 'No pending requests',
    'librarianDashboard.approve': 'Approve',
    'librarianDashboard.reject': 'Reject',
    'librarianDashboard.overdueBooks': 'Overdue Books',
    'librarianDashboard.pastDueDate': 'Books past due date requiring action',
    'librarianDashboard.noOverdueBooks': 'No overdue books',
    'librarianDashboard.due': 'Due',
    'librarianDashboard.confirmReturn': 'Confirm Return',
    'librarianDashboard.dueToday': 'Due Today',
    'librarianDashboard.expectedToday': 'Books expected to be returned today',
    'librarianDashboard.noBooksDueToday': 'No books due today',
    'librarianDashboard.received': 'Received',
    'librarianDashboard.viewAllBorrows': 'View All Borrows',
    'librarianDashboard.rejectReason': 'Reason for rejection (optional):',

    // MyBorrowsPage
    'myBorrowsPage.borrowed': 'Borrowed',
    'myBorrowsPage.returned': 'Returned',
    'myBorrowsPage.overdue': 'Overdue',
    'myBorrowsPage.loadFailed': 'Load failed',
    'myBorrowsPage.loadFailedMessage': 'Failed to load borrow history.',
    'myBorrowsPage.extended': 'Extended',
    'myBorrowsPage.extendedMessage': 'Borrow period has been extended.',
    'myBorrowsPage.extendFailed': 'Extend failed',
    'myBorrowsPage.extendFailedMessage': 'Unable to extend.',
    'myBorrowsPage.returned': 'Returned',
    'myBorrowsPage.returnedMessage': 'Book return request sent.',
    'myBorrowsPage.returnFailed': 'Return failed',
    'myBorrowsPage.returnFailedMessage': 'Unable to return.',
    'myBorrowsPage.dataFrom': 'Data from `/api/v1/borrows/history`.',
    'myBorrowsPage.loading': 'Loading records...',
    'myBorrowsPage.book': 'Book',
    'myBorrowsPage.borrowDate': 'Borrow Date',
    'myBorrowsPage.dueDate': 'Due Date',
    'myBorrowsPage.action': 'Action',
    'myBorrowsPage.noRecords': 'No records in this tab.',
    'myBorrowsPage.extend': 'Extend',
    'myBorrowsPage.return': 'Return',
    'myBorrowsPage.returnedFromUserPortal': 'Returned from user portal',
  },
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.books': 'Sách',
    'nav.categories': 'Danh mục',
    'nav.myBooks': 'Sách của tôi',
    'nav.favorites': 'Yêu thích',
    'nav.history': 'Lịch sử',
    'nav.profile': 'Hồ sơ',
    'nav.reviews': 'Đánh giá',
    'nav.dashboard': 'Bảng điều khiển',
    'nav.users': 'Người dùng',
    'nav.adminBooks': 'Quản lý Sách',
    'nav.adminBorrow': 'Quản lý Mượn',
    'nav.adminReservations': 'Đặt Sách',
    'nav.adminReservations': 'Đặt Sách',
    
    // Auth
    'auth.login': 'Đăng nhập',
    'auth.logout': 'Đăng xuất',
    'auth.register': 'Đăng ký',
    'auth.email': 'Email',
    'auth.password': 'Mật khẩu',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.firstName': 'Tên',
    'auth.lastName': 'Họ',
    'auth.alreadyHaveAccount': 'Đã có tài khoản?',
    'auth.dontHaveAccount': 'Chưa có tài khoản?',
    'auth.loginSuccess': 'Đăng nhập thành công',
    'auth.registerSuccess': 'Đăng ký thành công',
    'auth.loginFailed': 'Đăng nhập thất bại',
    'auth.registerFailed': 'Đăng ký thất bại',
    'auth.loginRequired': 'Thiếu mã truy cập. Vui lòng đăng nhập lại.',
    
    // Common
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.add': 'Thêm',
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.close': 'Đóng',
    'common.confirm': 'Xác nhận',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.total': 'Tổng',
    'common.status': 'Trạng thái',
    'common.actions': 'Hành động',
    
    // Book Labels (for forms, fields)
    'book.label.title': 'Tiêu đề',
    'book.label.author': 'Tác giả',
    'book.label.isbn': 'ISBN',
    'book.label.category': 'Danh mục',
    'book.label.description': 'Mô tả',
    'book.label.publisher': 'Nhà xuất bản',
    'book.label.publishedYear': 'Năm xuất bản',
    'book.label.pages': 'Số trang',
    'book.label.language': 'Ngôn ngữ',
    'book.label.uncategorized': 'Chưa phân loại',
    
    // Book Status
    'book.status.available': 'Có sẵn',
    'book.status.borrowed': 'Đã mượn',
    'book.status.reserved': 'Đã đặt',
    'book.status.outOfStock': 'Hết hàng',
    'book.status.archived': 'Lưu trữ',
    'book.status.damaged': 'Hư hỏng',
    
    // Book Actions
    'book.action.borrow': 'Mượn',
    'book.action.reserve': 'Đặt',
    'book.action.addToFavorites': 'Thêm vào yêu thích',
    'book.action.removeFromFavorites': 'Xóa khỏi yêu thích',
    'book.action.writeReview': 'Viết đánh giá',
    'book.action.viewDetails': 'Xem chi tiết',
    
    // Books Page
    'booksPage.title': 'Sách',
    'booksPage.searchPlaceholder': 'Tìm kiếm sách...',
    'booksPage.allCategories': 'Tất cả danh mục',
    'booksPage.allAuthors': 'Tất cả tác giả',
    'booksPage.allStatuses': 'Tất cả trạng thái',
    'booksPage.noBooksFound': 'Không tìm thấy sách nào',
    'booksPage.loading': 'Đang tải sách...',
    'booksPage.searchError': 'Không thể tải sách',
    'booksPage.clearFilters': 'Xóa bộ lọc',
    'booksPage.previous': 'Trước',
    'booksPage.next': 'Tiếp',
    'booksPage.page': 'Trang',
    'booksPage.of': 'của',
    
    // Dashboard
    'dashboard.totalUsers': 'Tổng người dùng',
    'dashboard.totalBooks': 'Tổng sách',
    'dashboard.borrowedBooks': 'Sách đã mượn',
    'dashboard.overdueBooks': 'Sách quá hạn',
    'dashboard.realTime': 'Thời gian thực',
    'dashboard.inventory': 'Tồn kho',
    'dashboard.active': 'Đang hoạt động',
    'dashboard.attention': 'Chú ý',
    'dashboard.synchronizing': 'Đang đồng bộ hóa phân tích cơ sở dữ liệu...',
    'dashboard.analyticsError': 'Lỗi Phân Tích',
    'dashboard.activityTimeline': 'Dòng hoạt động',
    'dashboard.performanceMetrics': 'Chỉ số hiệu suất 7 ngày từ dữ liệu trực tiếp',
    'dashboard.liveData': 'Dữ liệu trực tiếp',
    'dashboard.collectionGrowth': 'Tăng trưởng bộ sưu tập',
    'dashboard.databaseTrend': 'Xu hướng nhập cơ sở dữ liệu (Hàng tuần)',
    
    // User roles
    'role.admin': 'Quản trị viên',
    'role.librarian': 'Thủ thư',
    'role.user': 'Người dùng',
    
    // Status
    'status.active': 'Đang hoạt động',
    'status.inactive': 'Không hoạt động',
    'status.pending': 'Chờ xử lý',
    'status.approved': 'Đã duyệt',
    'status.rejected': 'Đã từ chối',
    'status.overdue': 'Quá hạn',
    'status.returned': 'Đã trả',
    'status.suspended': 'Tạm khóa',
    
    // Messages
    'message.bookBorrowed': 'Mượn sách thành công',
    'message.bookReturned': 'Trả sách thành công',
    'message.bookReserved': 'Đặt sách thành công',
    'message.errorOccurred': 'Đã xảy ra lỗi',
    'message.noDataFound': 'Không tìm thấy dữ liệu',
    
    // Date formats
    'date.today': 'Hôm nay',
    'date.yesterday': 'Hôm qua',
    'date.tomorrow': 'Ngày mai',
    
    // HomePage
    'home.discover': 'Khám Phá Sách Yêu Thích Tiếp Theo',
    'home.title': 'Duyệt dữ liệu danh mục trực tiếp, mượn nhanh và theo dõi mọi ngày hết hạn ở một nơi.',
    'home.description': 'Trang chủ này đọc dữ liệu thực từ các endpoint backend của bạn cho sách và lịch sử mượn.',
    'home.browseBooks': 'Duyệt Sách',
    'home.joinNow': 'Tham Gia Ngay',
    'home.myBooks': 'Sách Của Tôi',
    'home.catalogBooks': 'Sách danh mục',
    'home.activeBorrows': 'Đang mượn',
    'home.overdue': 'Quá hạn',
    'home.search': 'Tìm kiếm',
    'home.searchPlaceholder': 'Tìm kiếm sách...',
    'home.categoryFilter': 'Lọc danh mục',
    'home.authorFilter': 'Lọc tác giả',
    'home.featuredBooks': 'Sách Nổi Bật',
    'home.viewAll': 'Xem tất cả',
    'home.loadingBooks': 'Đang tải sách...',
    'home.noBooksFound': 'Không tìm thấy sách nào từ API.',
    'home.categories': 'Danh mục',
    'home.booksCount': 'sách',
    'home.categoryDataInfo': 'Dữ liệu danh mục sẽ xuất hiện khi sách có giá trị danh mục.',
    'home.accountActivity': 'Hoạt động tài khoản',
    'home.signedInAs': 'Đăng nhập với tư cách',
    'home.signInPrompt': 'Đăng nhập để xem hoạt động mượn sách của bạn.',
    'home.noBorrowHistory': 'Chưa có lịch sử mượn sách.',
    'home.available': 'có sẵn',
    'home.viewDetail': 'Xem Chi Tiết',
    'home.uncategorized': 'Chưa phân loại',
    'home.general': 'Chung',
    'home.record': 'Bản ghi',
    
    // AuthForms
    'auth.jwtAuthentication': 'Xác thực JWT',
    'auth.libraryAccess': 'Truy cập thư viện cho người dùng, thủ thư và quản trị viên.',
    'auth.secureAuth': 'Xác thực bảo mật với điều hướng nhận biết vai trò và tích hợp backend thực.',
    'auth.authApi': 'API Xác thực',
    'auth.authApiDesc': 'Đăng ký và đăng nhập endpoints',
    'auth.booksApi': 'API Sách',
    'auth.booksApiDesc': 'Dữ liệu danh mục và chi tiết trực tiếp',
    'auth.borrowApi': 'API Mượn',
    'auth.borrowApiDesc': 'Luồng mượn, trả và lịch sử',
    'auth.secureAccess': 'Truy cập bảo mật',
    'auth.loginTitle': 'Đăng nhập',
    'auth.createAccount': 'Tạo tài khoản',
    'auth.validationFailed': 'Xác thực thất bại',
    'auth.fixFields': 'Vui lòng sửa các trường được đánh dấu.',
    'auth.welcomeBack': 'Chào mừng trở lại',
    'auth.signInSuccess': 'Bạn đã đăng nhập thành công.',
    'auth.accountCreated': 'Tài khoản đã được tạo',
    'auth.accountReady': 'Tài khoản của bạn đã sẵn sàng sử dụng.',
    'auth.authFailed': 'Xác thực thất bại',
    'auth.unableToContinue': 'Không thể tiếp tục.',
    'auth.fullName': 'Họ và tên',
    'auth.fullNamePlaceholder': 'Nguyễn Hoàng Phụng',
    'auth.emailPlaceholder': 'ban@thuvien.com',
    'auth.passwordPlaceholder': '********',
    'auth.pleaseWait': 'Vui lòng đợi...',
    'auth.signIn': 'Đăng nhập',
    'auth.createAccountButton': 'Tạo tài khoản',
    'auth.fullNameRequired': 'Họ và tên là bắt buộc',
    'auth.emailRequired': 'Email là bắt buộc',
    'auth.invalidEmail': 'Định dạng email không hợp lệ',
    'auth.passwordRequired': 'Mật khẩu là bắt buộc',
    'auth.passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
    
    // DashboardCards
    'dashboardCards.totalBooks': 'Tổng Sách',
    'dashboardCards.totalBooksDesc': 'Tất cả sách trong thư viện',
    'dashboardCards.totalUsers': 'Tổng Người Dùng',
    'dashboardCards.totalUsersDesc': 'Thành viên đã đăng ký',
    'dashboardCards.activeBorrows': 'Đang Mượn',
    'dashboardCards.activeBorrowsDesc': 'Sách đang được mượn',
    'dashboardCards.overdueBooks': 'Quá Hạn',
    'dashboardCards.overdueBooksDesc': 'Sách quá hạn trả',
    
    // BookDetailPage
    'bookDetail.loading': 'Đang tải chi tiết sách...',
    'bookDetail.error': 'Không thể tải sách',
    'bookDetail.backToBooks': '← Trở về Sách',
    'bookDetail.addToFavorites': 'Thêm vào Yêu thích',
    'bookDetail.removeFromFavorites': 'Xóa khỏi Yêu thích',
    'bookDetail.borrow': 'Mượn',
    'bookDetail.reserve': 'Đặt',
    'bookDetail.writeReview': 'Viết Đánh giá',
    'bookDetail.details': 'Chi tiết',
    'bookDetail.description': 'Mô tả',
    'bookDetail.publisher': 'Nhà xuất bản',
    'bookDetail.publishedYear': 'Năm xuất bản',
    'bookDetail.pages': 'Số trang',
    'bookDetail.language': 'Ngôn ngữ',
    'bookDetail.isbn': 'ISBN',
    'bookDetail.category': 'Danh mục',
    'bookDetail.status': 'Trạng thái',
    'bookDetail.reviews': 'Đánh giá',
    'bookDetail.writeYourReview': 'Viết Đánh giá Của Bạn',
    'bookDetail.yourRating': 'Đánh giá của bạn',
    'bookDetail.yourReview': 'Nhận xét của bạn',
    'bookDetail.submitReview': 'Gửi Đánh giá',
    'bookDetail.postReview': 'Gửi Đánh giá',
    'bookDetail.posting': 'Đang gửi...',
    'bookDetail.loginToReview': 'Vui lòng đăng nhập để viết đánh giá',
    'bookDetail.recentReviews': 'Đánh giá Gần đây',
    'bookDetail.noReviewsYet': 'Chưa có đánh giá nào. Hãy là người đầu tiên!',
    'bookDetail.bookReserved': '📚 Đã đặt sách!',
    'bookDetail.bookReservedMessage': 'Sẵn sàng để nhận tại thư viện trong vòng 48 giờ. Vui lòng mang theo giấy tờ tùy thân để xác nhận và nhận sách. Trả sách muộn có thể bị tính phí phạt.',
    'bookDetail.borrowFailed': 'Mượn thất bại',
    'bookDetail.reserved': '🔔 Đã đặt!',
    'bookDetail.reservedMessage': 'Bạn sẽ được thông báo khi sách có sẵn.',
    'bookDetail.reservationFailed': 'Đặt sách thất bại',
    'bookDetail.reviewSubmitted': 'Đã gửi đánh giá!',
    'bookDetail.reviewSubmittedMessage': 'Cảm ơn phản hồi của bạn.',
    'bookDetail.failedToSubmit': 'Gửi thất bại',
    'bookDetail.failedLoadBook': 'Không thể tải dữ liệu sách',
    'bookDetail.available': 'Có sẵn',
    'bookDetail.unavailable': 'Không có sẵn',
    'bookDetail.noRatings': 'Chưa có đánh giá',
    'bookDetail.bookNotFound': 'Không tìm thấy sách',
    'bookDetail.saved': 'Đã lưu',
    'bookDetail.save': 'Lưu',
    'bookDetail.addedToFavorites': 'Đã thêm vào yêu thích',
    'bookDetail.removedFromFavorites': 'Đã xóa khỏi yêu thích',
    'bookDetail.share': 'Chia sẻ',
    'bookDetail.linkCopied': 'Đã sao chép link!',
    'bookDetail.quantity': 'Số lượng',
    'bookDetail.year': 'Năm',
    'bookDetail.processing': 'Đang xử lý...',
    'bookDetail.borrowNow': 'Mượn Ngay',
    'bookDetail.reserveBook': 'Đặt Sách',
    'bookDetail.peopleInQueue': 'người trong hàng chờ',
    'bookDetail.howRate': 'Bạn đánh giá sách này thế nào?',
    'bookDetail.reviewTitle': 'Tiêu đề Đánh giá',
    'bookDetail.reviewPlaceholder': 'Chia sẻ suy nghĩ của bạn về sách này...',
    
    // MyBorrowsPage
    'myBorrows.title': 'Sách Của Tôi',
    'myBorrows.dataFrom': 'Dữ liệu từ `/api/v1/borrows/history`.',
    'myBorrows.borrowed': 'Đã mượn',
    'myBorrows.returned': 'Đã trả',
    'myBorrows.overdue': 'Quá hạn',
    'myBorrows.loadingRecords': 'Đang tải bản ghi...',
    'myBorrows.book': 'Sách',
    'myBorrows.borrowDate': 'Ngày Mượn',
    'myBorrows.dueDate': 'Ngày Hết Hạn',
    'myBorrows.returnDate': 'Ngày Trả',
    'myBorrows.daysLeft': 'Còn lại',
    'myBorrows.overdueBy': 'Quá hạn',
    'myBorrows.extend': 'Gia hạn',
    'myBorrows.return': 'Trả',
    'myBorrows.noBorrowRecords': 'Không tìm thấy bản ghi mượn nào.',
    'myBorrows.extendSuccess': 'Gia hạn thành công',
    'myBorrows.extendFailed': 'Gia hạn thất bại',
    'myBorrows.returnSuccess': 'Trả sách thành công',
    'myBorrows.returnFailed': 'Trả sách thất bại',
    'myBorrows.status': 'Trạng thái',
    'myBorrows.action': 'Hành động',
    'myBorrows.noRecords': 'Không tìm thấy bản ghi nào.',
    'myBorrows.loadFailed': 'Không thể tải bản ghi',
    'myBorrows.loadFailedMessage': 'Không thể tải bản ghi mượn sách.',
    'myBorrows.extended': 'Đã gia hạn',
    'myBorrows.extendedMessage': 'Gia hạn thành công',
    'myBorrows.extendFailedMessage': 'Gia hạn thất bại',
    'myBorrows.returnedMessage': 'Trả sách thành công',
    'myBorrows.returnFailedMessage': 'Trả sách thất bại',
    
    // BorrowConfirmModal
    'borrowConfirm.title': 'Xác Nhận Mượn',
    'borrowConfirm.confirmBorrow': 'Xác Nhận Mượn',
    'borrowConfirm.borrowDetails': 'Chi Tiết Mượn',
    'borrowConfirm.book': 'Sách',
    'borrowConfirm.borrowDate': 'Ngày Mượn',
    'borrowConfirm.dueDate': 'Ngày Hết Hạn',
    'borrowConfirm.borrowPeriod': 'Thời Gian Mượn',
    'borrowConfirm.days': 'ngày',
    'borrowConfirm.borrowing': 'Đang mượn...',
    'borrowConfirm.borrowSuccess': 'Mượn sách thành công!',
    'borrowConfirm.borrowFailed': 'Mượn sách thất bại',
    'borrowConfirm.close': 'Đóng',
    
    // BookTable
    'bookTable.title': 'Quản Lý Sách',
    'bookTable.addBook': 'Thêm Sách',
    'bookTable.searchBooks': 'Tìm kiếm sách',
    'bookTable.searchTitleAuthorCategory': 'Tìm kiếm tiêu đề, tác giả, danh mục',
    'bookTable.searchPlaceholder': 'Tìm kiếm sách...',
    'bookTable.filterByCategory': 'Lọc theo Danh mục',
    'bookTable.filterByAuthor': 'Lọc theo Tác giả',
    'bookTable.filterByStatus': 'Lọc theo Trạng thái',
    'bookTable.clearFilters': 'Xóa Bộ Lọc',
    'bookTable.addNewBook': 'Thêm Sách Mới',
    'bookTable.bookTitle': 'Tiêu đề Sách',
    'bookTable.author': 'Tác giả',
    'bookTable.isbn': 'ISBN',
    'bookTable.category': 'Danh mục',
    'bookTable.status': 'Trạng thái',
    'bookTable.available': 'Có sẵn',
    'bookTable.outOfStock': 'Hết hàng',
    'bookTable.archived': 'Lưu trữ',
    'bookTable.damaged': 'Hư hỏng',
    'bookTable.noBooksFound': 'Không tìm thấy sách nào',
    'bookTable.loading': 'Đang tải sách...',
    'bookTable.edit': 'Sửa',
    'bookTable.delete': 'Xóa',
    'bookTable.showing': 'Hiển thị {count} của {total} sách',
    'bookTable.prev': 'Trước',
    'bookTable.next': 'Tiếp',
    'bookTable.editBook': 'Chỉnh sửa Sách',
    'bookTable.addBookTitle': 'Thêm Sách',
    'bookTable.totalQuantity': 'Tổng Số Lượng',
    'bookTable.saveBook': 'Lưu Sách',
    'bookTable.cancel': 'Hủy',
    'bookTable.deleteBook': 'Xóa Sách',
    'bookTable.confirmDelete': 'Bạn có chắc chắn muốn xóa sách này?',
    'bookTable.deleting': 'Đang xóa...',
    'bookTable.bookDeleted': 'Xóa sách thành công',
    'bookTable.deleteFailed': 'Xóa sách thất bại',
    'bookTable.saved': 'Lưu sách thành công',
    'bookTable.saveFailed': 'Lưu sách thất bại',
    'bookTable.stock': 'Tồn kho',
    'bookTable.loadFailedFallback': 'Không thể tải sách từ API. Đang hiển thị dữ liệu dự phòng.',
    'bookTable.requiredFields': 'Tiêu đề, ISBN và tổng số lượng là bắt buộc.',
    
    // UserTable
    'userTable.title': 'Quản Lý Người Dùng',
    'userTable.addUser': 'Thêm Người Dùng',
    'userTable.searchPlaceholder': 'Tìm kiếm người dùng...',
    'userTable.filterByRole': 'Lọc theo Vai trò',
    'userTable.filterByStatus': 'Lọc theo Trạng thái',
    'userTable.clearFilters': 'Xóa Bộ Lọc',
    'userTable.addNewUser': 'Thêm Người Dùng Mới',
    'userTable.fullName': 'Họ và tên',
    'userTable.email': 'Email',
    'userTable.role': 'Vai trò',
    'userTable.status': 'Trạng thái',
    'userTable.active': 'Đang hoạt động',
    'userTable.inactive': 'Không hoạt động',
    'userTable.noUsersFound': 'Không tìm thấy người dùng nào',
    'userTable.loading': 'Đang tải người dùng...',
    'userTable.edit': 'Sửa',
    'userTable.delete': 'Xóa',
    'userTable.showing': 'Hiển thị {count} của {total} người dùng',
    'userTable.prev': 'Trước',
    'userTable.next': 'Tiếp',
    'userTable.addUserTitle': 'Thêm Người Dùng',
    'userTable.editUserTitle': 'Sửa Người Dùng',
    'userTable.saveUser': 'Lưu Người Dùng',
    'userTable.cancel': 'Hủy',
    'userTable.deleteUser': 'Xóa Người Dùng',
    'userTable.confirmDelete': 'Bạn có chắc chắn muốn xóa người dùng này?',
    'userTable.deleting': 'Đang xóa...',
    'userTable.userDeleted': 'Xóa người dùng thành công',
    'userTable.deleteFailed': 'Xóa người dùng thất bại',
    'userTable.saved': 'Lưu người dùng thành công',
    'userTable.saveFailed': 'Lưu người dùng thất bại',
    'userTable.searchUsers': 'Tìm kiếm người dùng',
    'userTable.searchNameEmail': 'Tìm kiếm tên, email',
    'userTable.addUserButton': 'Thêm Người Dùng',
    'userTable.fullNameHeader': 'Họ và tên',
    'userTable.emailHeader': 'Email',
    'userTable.roleHeader': 'Vai trò',
    'userTable.statusHeader': 'Trạng thái',
    'userTable.lastLoginHeader': 'Đăng nhập cuối',
    'userTable.actionsHeader': 'Hành động',
    'userTable.loadingUsers': 'Đang tải người dùng...',
    'userTable.editButton': 'Sửa',
    'userTable.deleteButton': 'Xóa',
    'userTable.passwordLabel': 'Mật khẩu',
    'userTable.passwordOptional': 'Mật khẩu (để trống để giữ nguyên)',
    'userTable.loadFailed': 'Không thể tải người dùng.',
    'userTable.fullNameEmailRequired': 'Họ tên và email là bắt buộc.',
    'userTable.passwordRequiredCreate': 'Mật khẩu là bắt buộc khi tạo người dùng.',
    
    // AdminDashboard
    'adminDashboard.controlPanel': 'Bảng Điều Khiển Admin',
    'adminDashboard.welcomeBack': 'Chào mừng trở lại, {name}!',
    'adminDashboard.yourRole': 'Vai trò của bạn: {role} | Quản lý hoạt động thư viện hiệu quả',
    'adminDashboard.bookManagement': 'Quản Lý Sách',
    'adminDashboard.bookManagementDesc': 'Thêm, sửa, xóa sách và quản lý tồn kho',
    'adminDashboard.userManagement': 'Quản Lý Người Dùng',
    'adminDashboard.userManagementDesc': 'Quản lý người dùng, vai trò và quyền hạn',
    'adminDashboard.borrowManagement': 'Quản Lý Mượn',
    'adminDashboard.borrowManagementDesc': 'Theo dõi và quản lý yêu cầu mượn sách',
    'adminDashboard.borrowWorkflow': 'Quy Trình Mượn Sách',
    'adminDashboard.borrowWorkflowDesc': 'Xử lý yêu cầu mượn và quản lý trả sách',
    'adminDashboard.reservationManagement': 'Quản Lý Đặt Sách',
    'adminDashboard.reservationManagementDesc': 'Xử lý đặt sách và thông báo',
    'adminDashboard.reservations': 'Đặt Sách',
    'adminDashboard.reservationsDesc': 'Xem và quản lý đặt sách',
    'adminDashboard.systemSettings': 'Cài Đặt Hệ Thống',
    'adminDashboard.systemSettingsDesc': 'Cấu hình chính sách, tiền phạt và thông báo',
    'adminDashboard.open': 'Mở',
    'adminDashboard.systemStatus': 'Trạng Thái Hệ Thống',
    'adminDashboard.backend': 'Backend: {status}',
    'adminDashboard.checking': 'Đang kiểm tra...',
    'adminDashboard.connected': 'Đã kết nối - API đang hoạt động',
    'adminDashboard.error': 'Lỗi: {error}',
    'adminDashboard.online': 'Trực tuyến',
    'adminDashboard.offline': 'Ngoại tuyến',
    
    // LibrarianDashboard
    'librarianDashboard.workstation': 'Trạm Làm Việc Thủ Thư',
    'librarianDashboard.welcome': 'Chào mừng, {name}!',
    'librarianDashboard.roleDesc': 'Vai trò: {role} | Xử lý yêu cầu mượn sách và quản lý trả sách',
    'librarianDashboard.pendingApprovals': 'Chờ Duyệt',
    'librarianDashboard.overdueBooks': 'Sách Quá Hạn',
    'librarianDashboard.dueToday': 'Hết Hạn Hôm Nay',
    'librarianDashboard.noPending': 'Không có yêu cầu mượn nào đang chờ',
    'librarianDashboard.noOverdue': 'Không có sách quá hạn',
    'librarianDashboard.noDueToday': 'Không có sách nào hết hạn hôm nay',
    'librarianDashboard.approve': 'Duyệt',
    'librarianDashboard.reject': 'Từ chối',
    'librarianDashboard.confirmReturn': 'Xác Nhận Trả',
    'librarianDashboard.processing': 'Đang xử lý...',
    'librarianDashboard.approved': 'Yêu cầu đã được duyệt',
    'librarianDashboard.rejected': 'Yêu cầu đã bị từ chối',
    'librarianDashboard.returned': 'Sách đã được trả',
    'librarianDashboard.failed': 'Thao tác thất bại',
    'librarianDashboard.pendingBorrowRequests': 'Yêu cầu mượn đang chờ',
    'librarianDashboard.reviewAndApprove': 'Xem xét và duyệt yêu cầu mượn sách',
    'librarianDashboard.noPendingRequests': 'Không có yêu cầu nào đang chờ',
    'librarianDashboard.requiresAttention': 'Cần chú ý',
    'librarianDashboard.overdueBooksTitle': 'Sách Quá Hạn',
    'librarianDashboard.booksPastDue': 'Sách quá hạn cần xử lý',
    'librarianDashboard.noBooksDueToday': 'Không có sách nào hết hạn hôm nay',
    'librarianDashboard.enterRejectionReason': 'Nhập lý do từ chối (tùy chọn):',
    'librarianDashboard.loading': 'Đang tải...',
    'librarianDashboard.refresh': 'Làm mới',
    
    // BookCoverUpload
    'bookCoverUpload.onlyJpgPngWebp': 'Chỉ hỗ trợ JPG, PNG, WEBP.',
    'bookCoverUpload.maxSize2mb': 'Dung lượng tối đa 2MB.',
    'bookCoverUpload.uploadFailed': 'Tải lên thất bại với trạng thái {status}',
    'bookCoverUpload.uploadError': 'Lỗi khi tải lên.',
    'bookCoverUpload.downloadFailed': 'Tải xuống thất bại với trạng thái {status}',
    'bookCoverUpload.downloadError': 'Lỗi khi tải xuống ảnh từ URL.',
    'bookCoverUpload.deleteFailed': 'Xóa thất bại',
    'bookCoverUpload.deleteError': 'Lỗi khi xóa ảnh bìa.',
    'bookCoverUpload.confirmDelete': 'Bạn có chắc chắn muốn xóa ảnh bìa này không?',
    'bookCoverUpload.coverPreview': 'Xem trước ảnh bìa',
    'bookCoverUpload.noCover': 'Chưa có ảnh bìa',
    'bookCoverUpload.manageCover': 'Quản Lý Ảnh Bìa',
    'bookCoverUpload.dragDropOrClick': 'Kéo thả hoặc Nhấn chọn file',
    'bookCoverUpload.supportedFormats': 'JPG, PNG, WEBP lên tới 2MB',
    'bookCoverUpload.enterUrl': 'Nhập URL tải xuống',
    'bookCoverUpload.download': 'Tải',
    'bookCoverUpload.cancel': 'Hủy',
    'bookCoverUpload.deleteImage': 'Xóa ảnh',
    
    // BorrowManagement
    'borrowManagement.unableToLoad': 'Không thể tải bản ghi mượn sách.',
    'borrowManagement.approved': 'Đã duyệt',
    'borrowManagement.approvedMessage': 'Yêu cầu mượn sách đã được duyệt!',
    'borrowManagement.rejected': 'Đã từ chối',
    'borrowManagement.rejectedMessage': 'Yêu cầu mượn sách đã bị từ chối.',
    'borrowManagement.returned': 'Đã trả',
    'borrowManagement.returnedMessage': 'Sách đã được trả thành công.',
    'borrowManagement.extended': 'Đã gia hạn',
    'borrowManagement.extendedMessage': 'Thời gian mượn đã được gia hạn 7 ngày.',
    'borrowManagement.error': 'Lỗi',
    'borrowManagement.rejectReason': 'Lý do từ chối (tùy chọn):',
    'borrowManagement.activeBorrows': 'Đang mượn',
    'borrowManagement.overdueItems': 'Quá hạn',
    'borrowManagement.returnedItems': 'Đã trả',
    'borrowManagement.searchRecords': 'Tìm kiếm bản ghi mượn sách',
    'borrowManagement.searchPlaceholder': 'Tìm kiếm người dùng, sách hoặc trạng thái',
    'borrowManagement.all': 'Tất cả',
    'borrowManagement.pending': 'Chờ duyệt',
    'borrowManagement.borrowed': 'Đã mượn',
    'borrowManagement.returned': 'Đã trả',
    'borrowManagement.overdue': 'Quá hạn',
    'borrowManagement.loading': 'Đang tải bản ghi mượn sách...',
    'borrowManagement.noRecords': 'Không tìm thấy bản ghi nào.',
    'borrowManagement.borrower': 'Người mượn',
    'borrowManagement.borrowDate': 'Ngày mượn',
    'borrowManagement.dueDate': 'Ngày hết hạn',
    'borrowManagement.approve': 'Duyệt',
    'borrowManagement.reject': 'Từ chối',
    'borrowManagement.return': 'Trả',
    'borrowManagement.extend': 'Gia hạn',
    
    // ReservationTable
    'reservationTable.failedToLoad': 'Không thể tải đặt sách',
    'reservationTable.bookReservations': 'Đặt Sách',
    'reservationTable.allStatuses': 'Tất Cả Trạng Thái',
    'reservationTable.active': 'Đang hoạt động',
    'reservationTable.fulfilled': 'Đã hoàn thành',
    'reservationTable.cancelled': 'Đã hủy',
    'reservationTable.expired': 'Đã hết hạn',
    'reservationTable.loading': 'Đang tải đặt sách...',
    'reservationTable.noReservations': 'Không tìm thấy đặt sách nào.',
    'reservationTable.book': 'Sách',
    'reservationTable.user': 'Người dùng',
    'reservationTable.priority': 'Ưu tiên',
    'reservationTable.status': 'Trạng thái',
    'reservationTable.reservedAt': 'Ngày đặt',
    'reservationTable.expiresAt': 'Ngày hết hạn',
    'reservationTable.actions': 'Hành động',
    'reservationTable.normal': 'Bình thường',
    'reservationTable.high': 'Cao',
    'reservationTable.urgent': 'Khẩn cấp',
    'reservationTable.fulfill': 'Hoàn thành',
    'reservationTable.cancel': 'Hủy',
    'reservationTable.confirmCancel': 'Bạn có chắc chắn muốn hủy đặt sách này?',
    'reservationTable.confirmFulfill': 'Đánh dấu đặt sách này là đã hoàn thành?',
    
    // Sidebar
    'sidebar.dashboard': 'Bảng điều khiển',
    'sidebar.userManagement': 'Quản lý người dùng',
    'sidebar.bookService': 'Dịch vụ sách',
    'sidebar.borrowService': 'Dịch vụ mượn',
    'sidebar.reservations': 'Đặt sách',
    'sidebar.settings': 'Cài đặt',
    'sidebar.workDashboard': 'Bảng điều khiển công việc',
    'sidebar.borrowRequests': 'Yêu cầu mượn',
    'sidebar.bookInventory': 'Tồn kho sách',
    'sidebar.profile': 'Hồ sơ',
    'sidebar.adminSuite': 'Bộ Admin',
    'sidebar.librarianSuite': 'Bộ Thủ thư',
    'sidebar.library': 'Thư viện',
    'sidebar.signedInAs': 'Đăng nhập với tư cách',
    'sidebar.adminUser': 'Người dùng Admin',
    'sidebar.lightMode': 'Chế độ sáng',
    'sidebar.darkMode': 'Chế độ tối',

    // CategoriesPage
    'categoriesPage.title': 'Danh mục',
    'categoriesPage.description': 'Tổng hợp từ phản hồi `/api/v1/books`.',
    'categoriesPage.loading': 'Đang tải danh mục...',
    'categoriesPage.noCategories': 'Không tìm thấy danh mục nào',
    'categoriesPage.uncategorized': 'Chưa phân loại',
    'categoriesPage.booksCount': 'sách',

    // FavoritesPage
    'favoritesPage.title': 'Yêu thích',
    'favoritesPage.description': 'Sử dụng ID yêu thích cục bộ và lấy từng sách từ API.',
    'favoritesPage.loading': 'Đang tải yêu thích...',
    'favoritesPage.noFavorites': 'Chưa có sách yêu thích nào',
    'favoritesPage.addToFavorites': 'Thêm sách vào yêu thích để xem ở đây',

    // ProfilePage
    'profilePage.title': 'Hồ sơ',
    'profilePage.description': 'Danh tính hiện tại từ payload token đã xác thực.',
    'profilePage.fullName': 'Họ và tên',
    'profilePage.email': 'Email',
    'profilePage.role': 'Vai trò',
    'profilePage.userId': 'ID Người dùng',
    'profilePage.editNotAvailable': 'Endpoint chỉnh sửa hồ sơ chưa có sẵn trong API backend hiện tại.',

    // HistoryPage
    'historyPage.title': 'Lịch sử',
    'historyPage.description': 'Lịch sử mượn sách đầy đủ của bạn',
    'historyPage.loading': 'Đang tải lịch sử...',
    'historyPage.noHistory': 'Không có lịch sử nào',

    // ReviewsPage
    'reviewsPage.title': 'Đánh giá',
    'reviewsPage.description': 'Đánh giá và xếp hạng sách của bạn',
    'reviewsPage.loading': 'Đang tải đánh giá...',
    'reviewsPage.noReviews': 'Chưa có đánh giá nào',
    'reviewsPage.writeFirstReview': 'Viết đánh giá đầu tiên của bạn',

    // ReservationsPage
    'reservationsPage.title': 'Đặt chỗ',
    'reservationsPage.description': 'Quản lý đặt chỗ sách của bạn',
    'reservationsPage.loading': 'Đang tải đặt chỗ...',
    'reservationsPage.noReservations': 'Không tìm thấy đặt chỗ nào',
    'reservationsPage.makeReservation': 'Tạo Đặt chỗ',
    'reservationsPage.cancelReservation': 'Hủy Đặt chỗ',

    // BorrowBookPage
    'borrowBookPage.title': 'Mượn Sách',
    'borrowBookPage.description': 'Mượn sách từ thư viện',
    'borrowBookPage.selectBook': 'Chọn sách để mượn',
    'borrowBookPage.borrowPeriod': 'Thời Gian Mượn',
    'borrowBookPage.confirmBorrow': 'Xác Nhận Mượn',

    // BorrowPage
    'borrowPage.title': 'Mượn',
    'borrowPage.description': 'Quản lý mượn',
    'borrowPage.loading': 'Đang tải...',

    // BookPage
    'bookPage.title': 'Sách',
    'bookPage.description': 'Chi tiết và thông tin sách',
    'bookPage.loading': 'Đang tải sách...',

    // DashboardPage
    'dashboardPage.title': 'Bảng điều khiển',
    'dashboardPage.description': 'Bảng điều khiển quản lý thư viện',
    'dashboardPage.loading': 'Đang tải bảng điều khiển...',

    // UserPage
    'userPage.title': 'Người dùng',
    'userPage.description': 'Quản lý người dùng',
    'userPage.loading': 'Đang tải người dùng...',

    // AdminHomePageLegacy
    'adminHomePageLegacy.title': 'Trang Chủ Admin',
    'adminHomePageLegacy.description': 'Trang chủ admin cũ',

    // ThemeToggle
    'themeToggle.light': 'Sáng',
    'themeToggle.dark': 'Tối',
    'themeToggle.toggleTheme': 'Chuyển đổi chủ đề',

    // Toast
    'toast.success': 'Thành công',
    'toast.error': 'Lỗi',
    'toast.warning': 'Cảnh báo',
    'toast.info': 'Thông tin',

    // Input
    'input.required': 'Bắt buộc',
    'input.optional': 'Tùy chọn',

    // Dropdown
    'dropdown.selectOption': 'Chọn một tùy chọn',
    'dropdown.noOptions': 'Không có tùy chọn nào',

    // Modal
    'modal.close': 'Đóng',

    // Layout
    'layout.loading': 'Đang tải...',
    'layout.error': 'Lỗi tải nội dung',

    // Login
    'login.title': 'Đăng nhập',
    'login.description': 'Đăng nhập vào tài khoản của bạn',

    // DashboardLayout
    'dashboardLayout.loading': 'Đang tải bảng điều khiển...',
    'dashboardLayout.error': 'Lỗi tải bảng điều khiển',

    // RoleBasedDashboard
    'roleBasedDashboard.loading': 'Đang tải bảng điều khiển...',
    'roleBasedDashboard.error': 'Lỗi tải bảng điều khiển',

    // DashboardCards
    'dashboardCards.loading': 'Đang tải thống kê...',
    'dashboardCards.error': 'Lỗi tải thống kê',

    // AuthForms
    'auth.jwtAuthentication': 'Xác thực JWT',
    'auth.libraryAccess': 'Truy cập thư viện cho người dùng, thủ thư và quản trị viên.',
    'auth.secureAuth': 'Xác thực bảo mật với điều hướng vai trò và tích hợp backend thực.',
    'auth.authApi': 'API Xác thực',
    'auth.authApiDesc': 'Điểm cuối đăng ký và đăng nhập',
    'auth.booksApi': 'API Sách',
    'auth.booksApiDesc': 'Dữ liệu danh mục trực tiếp và chi tiết',
    'auth.borrowApi': 'API Mượn',
    'auth.borrowApiDesc': 'Mượn, trả và luồng lịch sử',
    'auth.secureAccess': 'Truy cập bảo mật',
    'auth.loginTitle': 'Đăng nhập',
    'auth.createAccount': 'Tạo tài khoản',
    'auth.validationFailed': 'Xác thực thất bại',
    'auth.fixFields': 'Vui lòng sửa các trường được đánh dấu.',
    'auth.signInSuccess': 'Bạn đã đăng nhập thành công.',
    'auth.accountCreated': 'Tài khoản đã được tạo',
    'auth.accountReady': 'Tài khoản của bạn đã sẵn sàng để sử dụng.',
    'auth.authFailed': 'Xác thực thất bại',
    'auth.unableToContinue': 'Không thể tiếp tục.',
    'auth.signIn': 'Đăng nhập',
    'auth.createAccountButton': 'Tạo tài khoản',
    'auth.fullNamePlaceholder': 'Nguyễn Hoàng Phùng',
    'auth.emailPlaceholder': 'ban@thuviện.com',
    'auth.passwordPlaceholder': '********',
    'auth.pleaseWait': 'Vui lòng đợi...',
    'auth.fullNameRequired': 'Họ tên là bắt buộc',
    'auth.invalidEmail': 'Định dạng email không hợp lệ',
    'auth.passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
    'auth.dontHaveAccount': 'Chưa có tài khoản? ',
    'auth.alreadyHaveAccount': 'Đã có tài khoản? ',

    // BookCoverUpload
    'bookCoverUpload.onlyJpgPngWebp': 'Chỉ hỗ trợ JPG, PNG, WEBP.',
    'bookCoverUpload.maxSize2mb': 'Dung lượng tối đa 2MB.',
    'bookCoverUpload.uploadFailed': 'Tải lên thất bại với trạng thái {status}',
    'bookCoverUpload.uploadError': 'Lỗi khi tải lên.',
    'bookCoverUpload.downloadFailed': 'Tải xuống thất bại với trạng thái {status}',
    'bookCoverUpload.downloadError': 'Lỗi khi tải xuống ảnh từ URL.',
    'bookCoverUpload.deleteFailed': 'Xóa thất bại',
    'bookCoverUpload.deleteError': 'Lỗi khi xóa ảnh bìa.',
    'bookCoverUpload.confirmDelete': 'Bạn có chắc chắn muốn xóa ảnh bìa này không?',
    'bookCoverUpload.coverPreview': 'Xem trước ảnh bìa',
    'bookCoverUpload.noCover': 'Chưa có ảnh bìa',
    'bookCoverUpload.manageCover': 'Quản Lý Ảnh Bìa',
    'bookCoverUpload.dragDropOrClick': 'Kéo thả hoặc Nhấn chọn file',
    'bookCoverUpload.supportedFormats': 'JPG, PNG, WEBP lên tới 2MB',
    'bookCoverUpload.enterUrl': 'Nhập URL tải xuống',
    'bookCoverUpload.download': 'Tải',
    'bookCoverUpload.deleteImage': 'Xóa ảnh',

    // Common
    'common.overview': 'Tổng quan',

    // Additional missing keys for components
    'bookTable.stock': 'Kho',
    'bookTable.saved': 'Đã lưu',
    'bookTable.saveFailed': 'Lưu thất bại',
    'bookTable.confirmDelete': 'Bạn có chắc chắn muốn xóa sách này không?',
    'bookTable.bookDeleted': 'Đã xóa sách',
    'bookTable.deleteFailed': 'Xóa thất bại',
    'bookTable.bookTitle': 'Tiêu đề sách',
    'bookTable.author': 'Tác giả',
    'bookTable.category': 'Danh mục',
    'bookTable.isbn': 'ISBN',
    'bookTable.status': 'Trạng thái',
    'bookTable.actions': 'Hành động',
    'bookTable.filterByCategory': 'Lọc theo danh mục',
    'bookTable.filterByAuthor': 'Lọc theo tác giả',
    'bookTable.filterByStatus': 'Lọc theo trạng thái',
    'bookTable.clearFilters': 'Xóa bộ lọc',
    'bookTable.totalQuantity': 'Tổng số lượng',
    'bookTable.saveBook': 'Lưu Sách',
    'bookTable.prev': 'Trước',
    'bookTable.next': 'Sau',
    'bookTable.showing': 'Hiển thị {count} của {total} {total, plural, one {sách} other {sách}}',
    'bookTable.available': 'Có sẵn',
    'bookTable.outOfStock': 'Hết hàng',
    'bookTable.archived': 'Đã lưu trữ',
    'bookTable.damaged': 'Hư hỏng',
    'bookTable.editBook': 'Sửa Sách',
    'bookTable.addBookTitle': 'Thêm Sách',

    'borrowConfirm.title': 'Xác nhận Yêu cầu',
    'borrowConfirm.confirmBorrow': 'Mượn sách này',
    'borrowConfirm.borrowDate': 'Mượn',
    'borrowConfirm.dueDate': 'Hết hạn',
    'borrowConfirm.borrowPeriod': 'Gia hạn',
    'borrowConfirm.days': 'ngày',
    'borrowConfirm.borrowing': 'Đang gửi...',

    'borrowManagement.activeBorrows': 'Đang mượn',
    'borrowManagement.overdueItems': 'Quá hạn',
    'borrowManagement.returnedItems': 'Đã trả',
    'borrowManagement.all': 'Tất cả',
    'borrowManagement.pending': 'Chờ xử lý',
    'borrowManagement.borrowed': 'Đã mượn',
    'borrowManagement.returned': 'Đã trả',
    'borrowManagement.overdue': 'Quá hạn',
    'borrowManagement.searchRecords': 'Tìm kiếm bản ghi mượn',
    'borrowManagement.searchPlaceholder': 'Tìm kiếm người dùng, sách hoặc trạng thái',
    'borrowManagement.loading': 'Đang tải bản ghi mượn...',
    'borrowManagement.noRecords': 'Không tìm thấy bản ghi nào.',
    'borrowManagement.borrower': 'Người mượn',
    'borrowManagement.borrowDate': 'Ngày mượn',
    'borrowManagement.dueDate': 'Ngày hết hạn',
    'borrowManagement.approve': 'Duyệt',
    'borrowManagement.reject': 'Từ chối',
    'borrowManagement.return': 'Trả',
    'borrowManagement.extend': 'Gia hạn',
    'borrowManagement.approved': 'Đã duyệt',
    'borrowManagement.approvedMessage': 'Yêu cầu mượn đã được duyệt!',
    'borrowManagement.rejected': 'Đã từ chối',
    'borrowManagement.rejectedMessage': 'Yêu cầu mượn đã bị từ chối.',
    'borrowManagement.returned': 'Đã trả',
    'borrowManagement.returnedMessage': 'Sách đã được trả thành công.',
    'borrowManagement.extended': 'Đã gia hạn',
    'borrowManagement.extendedMessage': 'Thời gian mượn đã được gia hạn 7 ngày.',
    'borrowManagement.error': 'Lỗi',
    'borrowManagement.unableToLoad': 'Không thể tải bản ghi mượn.',
    'borrowManagement.rejectReason': 'Lý do từ chối (tùy chọn):',

    'reservationTable.bookReservations': 'Đặt chỗ Sách',
    'reservationTable.allStatuses': 'Tất cả Trạng thái',
    'reservationTable.active': 'Đang hoạt động',
    'reservationTable.fulfilled': 'Đã hoàn thành',
    'reservationTable.cancelled': 'Đã hủy',
    'reservationTable.expired': 'Đã hết hạn',
    'reservationTable.book': 'Sách',
    'reservationTable.user': 'Người dùng',
    'reservationTable.priority': 'Ưu tiên',
    'reservationTable.status': 'Trạng thái',
    'reservationTable.reservedAt': 'Đặt lúc',
    'reservationTable.expiresAt': 'Hết hạn lúc',
    'reservationTable.actions': 'Hành động',
    'reservationTable.loading': 'Đang tải đặt chỗ...',
    'reservationTable.noReservations': 'Không tìm thấy đặt chỗ nào.',
    'reservationTable.failedToLoad': 'Không thể tải đặt chỗ',
    'reservationTable.confirmCancel': 'Bạn có chắc chắn muốn hủy đặt chỗ này không?',
    'reservationTable.confirmFulfill': 'Đánh dấu đặt chỗ này là đã hoàn thành?',
    'reservationTable.fulfill': 'Hoàn thành',
    'reservationTable.cancel': 'Hủy',
    'reservationTable.normal': 'Bình thường',
    'reservationTable.high': 'Cao',
    'reservationTable.urgent': 'Khẩn cấp',

    'userTable.searchUsers': 'Tìm kiếm người dùng',
    'userTable.searchNameEmail': 'Tìm kiếm tên, email',
    'userTable.status': 'Trạng thái',
    'userTable.addUserButton': 'Thêm Người dùng',
    'userTable.fullNameHeader': 'Họ và tên',
    'userTable.emailHeader': 'Email',
    'userTable.roleHeader': 'Vai trò',
    'userTable.statusHeader': 'Trạng thái',
    'userTable.lastLoginHeader': 'Lần đăng nhập cuối',
    'userTable.actionsHeader': 'Hành động',
    'userTable.loadingUsers': 'Đang tải người dùng...',
    'userTable.editButton': 'Sửa',
    'userTable.deleteButton': 'Xóa',
    'userTable.showing': 'Hiển thị {count} của {total} người dùng',
    'userTable.addUserTitle': 'Thêm Người dùng',
    'userTable.editUserTitle': 'Sửa Người dùng',
    'userTable.passwordOptional': 'Mật khẩu (để trống để giữ hiện tại)',
    'userTable.saveUser': 'Lưu Người dùng',
    'userTable.saveFailed': 'Không thể lưu người dùng.',
    'userTable.deleteFailed': 'Không thể xóa người dùng.',

    // AdminDashboard
    'adminDashboard.checking': 'Đang kiểm tra...',
    'adminDashboard.connected': 'Đã kết nối - API đang hoạt động',
    'adminDashboard.error': 'Lỗi: HTTP {status}',
    'adminDashboard.controlPanel': 'Bảng điều khiển Quản trị viên',
    'adminDashboard.welcomeBack': 'Chào mừng trở lại, {name}',
    'adminDashboard.yourRole': 'Vai trò của bạn: ',
    'adminDashboard.manageOperations': '| Quản lý hoạt động thư viện của bạn một cách hiệu quả',
    'adminDashboard.bookManagement': 'Quản lý Sách',
    'adminDashboard.bookManagementDesc': 'Thêm, sửa, xóa sách và quản lý kho',
    'adminDashboard.userManagement': 'Quản lý Người dùng',
    'adminDashboard.userManagementDesc': 'Quản lý tài khoản người dùng, vai trò và quyền',
    'adminDashboard.borrowWorkflow': 'Luồng Mượn',
    'adminDashboard.borrowWorkflowDesc': 'Theo dõi yêu cầu mượn, trả và quá hạn',
    'adminDashboard.reservationsDesc': 'Quản lý đặt chỗ sách và danh sách chờ',
    'adminDashboard.systemSettings': 'Cài đặt Hệ thống',
    'adminDashboard.systemSettingsDesc': 'Cấu hình chính sách, phí và thông báo',
    'adminDashboard.open': 'Mở',
    'adminDashboard.systemStatus': 'Trạng thái Hệ thống',
    'adminDashboard.backend': 'Backend: ',
    'adminDashboard.online': 'Trực tuyến',
    'adminDashboard.offline': 'Ngoại tuyến',

    // BookDetail
    'bookDetail.borrowSuccess': 'Đã mượn sách thành công',
    'bookDetail.borrowSuccessMessage': 'Bạn đã mượn sách này thành công.',
    'bookDetail.reserveSuccess': 'Đã đặt chỗ sách thành công',
    'bookDetail.reserveSuccessMessage': 'Đặt chỗ của bạn đã được xác nhận.',
    'bookDetail.reviewValidationFailed': 'Xác thực đánh giá thất bại',
    'bookDetail.reviewValidationMessage': 'Vui lòng cung cấp xếp hạng và cả tiêu đề và nội dung.',
    'bookDetail.reviewPosted': 'Đã đăng đánh giá',
    'bookDetail.reviewPostedMessage': 'Đánh giá của bạn đã được đăng thành công.',
    'bookDetail.bookNotFound': 'Không tìm thấy Sách',
    'bookDetail.bookNotFoundMessage': 'Sách bạn đang tìm kiếm không tồn tại.',
    'bookDetail.backToBooks': 'Trở lại Sách',
    'bookDetail.available': 'Có sẵn',
    'bookDetail.unavailable': 'Không có sẵn',
    'bookDetail.linkCopied': 'Đã sao chép liên kết',
    'bookDetail.share': 'Chia sẻ',
    'bookDetail.quantity': 'Số lượng',
    'bookDetail.year': 'Năm',
    'bookDetail.isbn': 'ISBN',
    'bookDetail.description': 'Mô tả',
    'bookDetail.borrowNow': 'MƯỢN NGAY',
    'bookDetail.processing': 'Đang xử lý...',
    'bookDetail.reserveBook': 'ĐẶT CHỖ SÁCH',
    'bookDetail.peopleInQueue': '{count} người trong hàng đợi',
    'bookDetail.writeReview': 'Viết Đánh giá',
    'bookDetail.howRate': 'Bạn sẽ đánh giá thế nào?',
    'bookDetail.reviewTitlePlaceholder': 'Tiêu đề đánh giá của bạn',
    'bookDetail.reviewContentPlaceholder': 'Chia sẻ trải nghiệm của bạn với cuốn sách này...',
    'bookDetail.posting': 'Đang đăng...',
    'bookDetail.postReview': 'Đăng Đánh giá',
    'bookDetail.loginToReview': 'Vui lòng đăng nhập để viết đánh giá',
    'bookDetail.recentReviews': 'Đánh giá Gần đây',
    'bookDetail.noReviews': 'Chưa có đánh giá nào. Hãy là người đầu tiên!',

    // BooksPage
    'booksPage.category': 'Danh mục',
    'booksPage.author': 'Tác giả',
    'booksPage.availability': 'Khả dụng',
    'booksPage.allCategories': 'Tất cả Danh mục',
    'booksPage.allAuthors': 'Tất cả Tác giả',
    'booksPage.allStatuses': 'Tất cả Trạng thái',
    'booksPage.searchPlaceholder': 'Tìm kiếm theo tiêu đề, tác giả, hoặc ISBN...',
    'booksPage.loading': 'Đang tải sách...',
    'booksPage.failedToLoad': 'Không thể tải sách',
    'booksPage.viewDetail': 'Xem Chi tiết',
    'booksPage.noBooksFound': 'Không tìm thấy sách nào.',
    'booksPage.page': 'Trang {current} / {total}',

    // HomePage
    'homePage.discoverNextBook': 'Khám phá Sách Yêu thích Tiếp theo của Bạn',
    'homePage.browseDescription': 'Duyệt dữ liệu danh mục trực tiếp, mượn nhanh, và theo dõi mọi ngày hết hạn ở một nơi.',
    'homePage.readRealData': 'Trang chủ này đọc dữ liệu thực từ các điểm cuối backend của bạn cho sách và lịch sử mượn.',
    'homePage.browseBooks': 'Duyệt Sách',
    'homePage.joinNow': 'Tham gia Ngay',
    'homePage.catalogBooks': 'Sách Danh mục',
    'homePage.activeBorrows': 'Đang mượn',
    'homePage.overdue': 'Quá hạn',
    'homePage.search': 'Tìm kiếm',
    'homePage.searchBooks': 'Tìm kiếm sách...',
    'homePage.categoryFilter': 'Bộ lọc Danh mục',
    'homePage.authorFilter': 'Bộ lọc Tác giả',
    'homePage.featuredBooks': 'Sách Nổi bật',
    'homePage.viewAll': 'Xem tất cả',
    'homePage.loadingBooks': 'Đang tải sách...',
    'homePage.available': 'có sẵn',
    'homePage.noBooksFound': 'Không tìm thấy sách từ API.',
    'homePage.accountActivity': 'Hoạt động Tài khoản',
    'homePage.signedInAs': 'Đã đăng nhập với tư cách {name}',
    'homePage.signInToSeeActivity': 'Đăng nhập để xem hoạt động mượn của bạn.',
    'homePage.record': 'Bản ghi',
    'homePage.noBorrowHistory': 'Chưa có lịch sử mượn nào.',
    'homePage.categoryDataWillAppear': 'Dữ liệu danh mục sẽ xuất hiện khi sách bao gồm các giá trị danh mục.',

    // LibrarianDashboard
    'librarianDashboard.librarianPanel': 'Bảng điều khiển Thủ thư',
    'librarianDashboard.welcomeBack': 'Chào mừng trở lại, {name}',
    'librarianDashboard.manageLibrary': 'Quản lý hoạt động thư viện và hỗ trợ người dùng một cách hiệu quả.',
    'librarianDashboard.totalBooks': 'Tổng Sách',
    'librarianDashboard.activeBorrows': 'Đang mượn',
    'librarianDashboard.pendingApprovals': 'Chờ duyệt',
    'librarianDashboard.overdueItems': 'Mục quá hạn',
    'librarianDashboard.requiresAttention': 'Yêu cầu sự chú ý',
    'librarianDashboard.pendingRequests': 'Yêu cầu Mượn Chờ duyệt',
    'librarianDashboard.reviewApprove': 'Xem xét và duyệt yêu cầu mượn',
    'librarianDashboard.user': 'Người dùng',
    'librarianDashboard.book': 'Sách',
    'librarianDashboard.requestDate': 'Ngày yêu cầu',
    'librarianDashboard.actions': 'Hành động',
    'librarianDashboard.noPendingRequests': 'Không có yêu cầu nào đang chờ',
    'librarianDashboard.approve': 'Duyệt',
    'librarianDashboard.reject': 'Từ chối',
    'librarianDashboard.overdueBooks': 'Sách Quá hạn',
    'librarianDashboard.pastDueDate': 'Sách quá ngày hết hạn yêu cầu hành động',
    'librarianDashboard.noOverdueBooks': 'Không có sách nào quá hạn',
    'librarianDashboard.due': 'Hết hạn',
    'librarianDashboard.confirmReturn': 'Xác nhận Trả',
    'librarianDashboard.dueToday': 'Hết hạn Hôm nay',
    'librarianDashboard.expectedToday': 'Sách dự kiến được trả hôm nay',
    'librarianDashboard.noBooksDueToday': 'Không có sách nào hết hạn hôm nay',
    'librarianDashboard.received': 'Đã nhận',
    'librarianDashboard.viewAllBorrows': 'Xem Tất cả Mượn',
    'librarianDashboard.rejectReason': 'Lý do từ chối (tùy chọn):',

    // MyBorrowsPage
    'myBorrowsPage.borrowed': 'Đã mượn',
    'myBorrowsPage.returned': 'Đã trả',
    'myBorrowsPage.overdue': 'Quá hạn',
    'myBorrowsPage.loadFailed': 'Tải thất bại',
    'myBorrowsPage.loadFailedMessage': 'Không thể tải lịch sử mượn.',
    'myBorrowsPage.extended': 'Đã gia hạn',
    'myBorrowsPage.extendedMessage': 'Thời gian mượn đã được gia hạn.',
    'myBorrowsPage.extendFailed': 'Gia hạn thất bại',
    'myBorrowsPage.extendFailedMessage': 'Không thể gia hạn.',
    'myBorrowsPage.returned': 'Đã trả',
    'myBorrowsPage.returnedMessage': 'Yêu cầu trả sách đã được gửi.',
    'myBorrowsPage.returnFailed': 'Trả thất bại',
    'myBorrowsPage.returnFailedMessage': 'Không thể trả.',
    'myBorrowsPage.dataFrom': 'Dữ liệu từ `/api/v1/borrows/history`.',
    'myBorrowsPage.loading': 'Đang tải bản ghi...',
    'myBorrowsPage.book': 'Sách',
    'myBorrowsPage.borrowDate': 'Ngày mượn',
    'myBorrowsPage.dueDate': 'Ngày hết hạn',
    'myBorrowsPage.action': 'Hành động',
    'myBorrowsPage.noRecords': 'Không có bản ghi nào trong tab này.',
    'myBorrowsPage.extend': 'Gia hạn',
    'myBorrowsPage.return': 'Trả',
    'myBorrowsPage.returnedFromUserPortal': 'Đã trả từ cổng người dùng',

    // BorrowBookPage
    'borrowBookPage.title': 'Mượn Sách',
    'borrowBookPage.borrowSuccess': 'Đã mượn sách thành công',
    'borrowBookPage.confirmBorrow': 'Xác nhận Mượn',

    // BorrowPage
    'borrowPage.description': 'Quản lý tất cả yêu cầu mượn và theo dõi tình trạng sẵn có của sách',

    // Dashboard
    'dashboard.libraryManagementSystem': 'Hệ thống Quản lý Thư viện',
    'dashboard.checking': 'Đang kiểm tra...',
    'dashboard.connected': 'Đã kết nối - API đang hoạt động',
    'dashboard.authRequired': 'Yêu cầu xác thực cho API',
    'dashboard.connectedUnauthorized': 'Đã kết nối nhưng không được ủy quyền',
    'dashboard.error': 'Lỗi: {status}',
    'dashboard.online': 'Trực tuyến',
    'dashboard.offline': 'Ngoại tuyến',
    'dashboard.welcome': 'Chào mừng trở lại, {name}',
    'dashboard.yourInformation': 'Thông tin của bạn',
    'dashboard.availableFeatures': 'Tính năng Có sẵn',
    'dashboard.bookManagement': 'Quản lý Sách',
    'dashboard.userManagement': 'Quản lý Người dùng',
    'dashboard.bookBorrowing': 'Mượn Sách',
    'dashboard.inventoryTracking': 'Theo dõi Kho',

    // DashboardPage
    'dashboardPage.premiumLibraryAdmin': 'Quản trị viên Thư viện Cao cấp',
    'dashboardPage.operateDescription': 'Vận hành thư viện của bạn như một nền tảng SaaS hiện đại.',
    'dashboardPage.manageDescription': 'Quản lý xác thực, người dùng, sách, luồng mượn và phân tích trong một bảng điều khiển được thiết kế cho dự án quản lý thư viện.',

    // BorrowBookPage
    'borrowBookPage.title': 'Borrow Book',
    'borrowBookPage.borrowSuccess': 'Book borrowed successfully',
    'borrowBookPage.confirmBorrow': 'Confirm Borrow',

    // BorrowPage
    'borrowPage.description': 'Manage all borrowing requests and track book availability',

    // Dashboard
    'dashboard.libraryManagementSystem': 'Library Management System',
    'dashboard.checking': 'Checking...',
    'dashboard.connected': 'Connected - API is working',
    'dashboard.authRequired': 'Authentication required for API',
    'dashboard.connectedUnauthorized': 'Connected but unauthorized',
    'dashboard.error': 'Error: {status}',
    'dashboard.online': 'Online',
    'dashboard.offline': 'Offline',
    'dashboard.welcome': 'Welcome, {name}',
    'dashboard.yourInformation': 'Your Information',
    'dashboard.availableFeatures': 'Available Features',
    'dashboard.bookManagement': 'Book Management',
    'dashboard.userManagement': 'User Management',
    'dashboard.bookBorrowing': 'Book Borrowing',
    'dashboard.inventoryTracking': 'Inventory Tracking',

    // DashboardPage
    'dashboardPage.premiumLibraryAdmin': 'Premium library admin',
    'dashboardPage.operateDescription': 'Operate your library like a modern SaaS platform.',
    'dashboardPage.manageDescription': 'Manage authentication, users, books, borrowing workflows, and analytics in a polished dashboard tailored for a library management project.',

    // AdminHomePageLegacy
    'adminHomePageLegacy.startExploring': 'Bắt đầu khám phá bộ sưu tập thư viện và quản lý sách đã mượn của bạn.',
    'adminHomePageLegacy.browseBooks': 'Duyệt Sách',
    'adminHomePageLegacy.inLibraryCollection': 'Trong bộ sưu tập thư viện của chúng tôi',
    'adminHomePageLegacy.manageInventory': 'Quản lý kho.',
    'adminHomePageLegacy.borrowWorkflow': 'Luồng Mượn',
    'adminHomePageLegacy.borrowWorkflowDesc': 'Theo dõi luồng mượn và trả và giám sát các bản ghi quá hạn.',
    'adminHomePageLegacy.userManagement': 'Quản lý Người dùng',
    'adminHomePageLegacy.userManagementDesc': 'Xem xét tài khoản người dùng, quyền và trạng thái tài khoản.',
    'adminHomePageLegacy.booksCurrentlyBorrowed': 'Sách hiện đang được mượn',
    'adminHomePageLegacy.booksOverdueReturn': 'Sách quá hạn cần trả',

    // AdminHomePageLegacy
    'adminHomePageLegacy.startExploring': 'Start exploring our library collection and manage your borrowed books.',
    'adminHomePageLegacy.browseBooks': 'Browse Books',
    'adminHomePageLegacy.inLibraryCollection': 'In our library collection',
    'adminHomePageLegacy.manageInventory': 'Manage inventory.',
    'adminHomePageLegacy.borrowWorkflow': 'Borrow Workflow',
    'adminHomePageLegacy.borrowWorkflowDesc': 'Track borrow and return workflows and monitor overdue records.',
    'adminHomePageLegacy.userManagement': 'User Management',
    'adminHomePageLegacy.userManagementDesc': 'Review user accounts, permissions, and account status.',
    'adminHomePageLegacy.booksCurrentlyBorrowed': 'Books currently being borrowed',
    'adminHomePageLegacy.booksOverdueReturn': 'Books overdue for return',
  }
};

const LanguageContext = createContext();

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get saved language from localStorage or default to Vietnamese
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage]) {
      return savedLanguage;
    }
    
    // Default to Vietnamese
    return 'vi';
  });

  // Enhanced translation function with fallback and parameter support
  const t = (key, params = {}) => {
    let text = 
      translations[language]?.[key] || 
      translations['en']?.[key] || 
      key;

    // Replace parameters
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });

    return text;
  };

  const changeLanguage = (newLanguage) => {
    if (translations[newLanguage]) {
      setLanguage(newLanguage);
      localStorage.setItem('language', newLanguage);
    }
  };

  // Sync language changes between tabs
  useEffect(() => {
    const handleStorage = (e) => {
      if (e.key === 'language') {
        const newLanguage = e.newValue;
        if (newLanguage && translations[newLanguage]) {
          setLanguage(newLanguage);
        }
      }
    };

    window.addEventListener('storage', handleStorage);
    return () => window.removeEventListener('storage', handleStorage);
  }, []);

  const availableLanguages = ['en', 'vi'];

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};
